// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6d1ac80c6e7bce05 "Projeto Chacal", do not edit manually */
"use client";

import { className, css, fonts } from "../chunks/chunk-XO7AUMAJ.js";
import { routes } from "../chunks/chunk-XLH7UDAO.js";

// virtual:button/button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/oAGXEvC9i9ipzDo1kBvB/lfBxNtox5KEd9f46hCoo/hoEBqMEaI.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["o0l93dZIx", "ojLAqizxh"];
var serializationHash = "framer-A1630";
var variantClassNames = {
	o0l93dZIx: "framer-v-14f5w8a",
	ojLAqizxh: "framer-v-27wmn2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var radiusForCorner = (value, cornerIndex) => {
	if (typeof value === "number" && Number.isFinite(value))
		return Math.max(0, value) + "px";
	if (typeof value !== "string" || typeof cornerIndex !== "number")
		return void 0;
	const segments = value.split(" ");
	return segments[cornerIndex] || segments[cornerIndex - 2] || segments[0];
};
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.7,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "o0l93dZIx",
	Hover: "ojLAqizxh",
};
var getProps = ({
	background,
	border,
	height,
	hoverBG,
	id,
	link,
	radius,
	title,
	width,
	...props
}) => {
	return {
		...props,
		ALaEy4Ra3:
			hoverBG ??
			props.ALaEy4Ra3 ??
			"var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19))",
		CfQsnK3E6: border ??
			props.CfQsnK3E6 ?? {
				borderColor:
					'var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223)) /* {"name":"White/80"} */',
				borderStyle: "solid",
				borderWidth: 1,
			},
		d9a9Ooocv: link ?? props.d9a9Ooocv,
		LAABUKeKB:
			background ??
			props.LAABUKeKB ??
			"var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(247, 247, 242))",
		TAyFC8rR3: title ?? props.TAyFC8rR3 ?? "Work",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "o0l93dZIx",
		YXuFuYjH_: radius ?? props.YXuFuYjH_ ?? "14px",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		LAABUKeKB,
		TAyFC8rR3,
		YXuFuYjH_,
		CfQsnK3E6,
		ALaEy4Ra3,
		d9a9Ooocv,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "o0l93dZIx",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnter1a4msnc = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("ojLAqizxh");
	});
	const onMouseLeave1281dia = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("o0l93dZIx");
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link href={d9a9Ooocv} nodeId={"o0l93dZIx"}>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-14f5w8a", className2, classNames)} framer-1brlyb4`}
							data-border={true}
							data-framer-name={"Default"}
							data-highlight={true}
							data-reset={"button"}
							layoutDependency={layoutDependency}
							layoutId={"o0l93dZIx"}
							onMouseEnter={onMouseEnter1a4msnc}
							ref={ref ?? ref1}
							style={{
								"--border-bottom-width":
									(CfQsnK3E6.borderBottomWidth ?? CfQsnK3E6.borderWidth) + "px",
								"--border-color": CfQsnK3E6.borderColor,
								"--border-left-width":
									(CfQsnK3E6.borderLeftWidth ?? CfQsnK3E6.borderWidth) + "px",
								"--border-right-width":
									(CfQsnK3E6.borderRightWidth ?? CfQsnK3E6.borderWidth) + "px",
								"--border-style": CfQsnK3E6.borderStyle,
								"--border-top-width":
									(CfQsnK3E6.borderTopWidth ?? CfQsnK3E6.borderWidth) + "px",
								backgroundColor: LAABUKeKB,
								borderBottomLeftRadius: radiusForCorner(YXuFuYjH_, 3),
								borderBottomRightRadius: radiusForCorner(YXuFuYjH_, 2),
								borderTopLeftRadius: radiusForCorner(YXuFuYjH_, 0),
								borderTopRightRadius: radiusForCorner(YXuFuYjH_, 1),
								...style,
							}}
							variants={{
								ojLAqizxh: {
									backgroundColor: ALaEy4Ra3,
								},
							}}
							{...addPropertyOverrides(
								{
									ojLAqizxh: {
										"data-framer-name": "Hover",
										onMouseLeave: onMouseLeave1281dia,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-19bl3x9"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"uOUM7DhUs"}
								style={{
									filter: "invert(1)",
									WebkitFilter: "invert(1)",
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-hgif0a"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"ELj89EkjU"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-7ab5faa8-d17b-41d2-8b42-49368cf2f4df, rgb(34, 39, 37))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={TAyFC8rR3}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-q12std"}
											data-styles-preset={"nZjNjGRCH"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-7ab5faa8-d17b-41d2-8b42-49368cf2f4df, rgb(34, 39, 37)))",
											}}
										>
											{"Work"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-c9n6ks"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"IP41ORbyP"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-7ab5faa8-d17b-41d2-8b42-49368cf2f4df, rgb(34, 39, 37))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={TAyFC8rR3}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-q12std"}
											data-styles-preset={"nZjNjGRCH"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-7ab5faa8-d17b-41d2-8b42-49368cf2f4df, rgb(34, 39, 37)))",
											}}
										>
											{"Work"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-A1630.framer-1brlyb4, .framer-A1630 .framer-1brlyb4 { display: block; }",
	".framer-A1630.framer-14f5w8a { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 8px 54px 8px 54px; position: relative; text-decoration: none; width: 200px; will-change: var(--framer-will-change-override, transform); }",
	".framer-A1630 .framer-19bl3x9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 21px; justify-content: flex-start; mix-blend-mode: difference; overflow: hidden; padding: 0px; position: relative; width: min-content; z-index: 2; }",
	".framer-A1630 .framer-hgif0a, .framer-A1630 .framer-c9n6ks { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-A1630.framer-14f5w8a, .framer-A1630 .framer-19bl3x9 { gap: 0px; } .framer-A1630.framer-14f5w8a > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-A1630.framer-14f5w8a > :first-child { margin-left: 0px; } .framer-A1630.framer-14f5w8a > :last-child { margin-right: 0px; } .framer-A1630 .framer-19bl3x9 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-A1630 .framer-19bl3x9 > :first-child { margin-top: 0px; } .framer-A1630 .framer-19bl3x9 > :last-child { margin-bottom: 0px; } }",
	".framer-A1630.framer-v-27wmn2 .framer-19bl3x9 { justify-content: flex-end; }",
	...css,
	'.framer-A1630[data-border="true"]::after, .framer-A1630 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerhoEBqMEaI = withCSS(Component, css2, "framer-A1630");
var stdin_default = FramerhoEBqMEaI;
FramerhoEBqMEaI.displayName = "Button/Button";
FramerhoEBqMEaI.defaultProps = {
	height: 37,
	width: 200,
};
addPropertyControls(FramerhoEBqMEaI, {
	variant: {
		options: ["o0l93dZIx", "ojLAqizxh"],
		optionTitles: ["Default", "Hover"],
		title: "Variant",
		type: ControlType.Enum,
	},
	LAABUKeKB: {
		defaultValue:
			'var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(247, 247, 242)) /* {"name":"BG"} */',
		title: "Background",
		type: ControlType.Color,
	},
	TAyFC8rR3: {
		defaultValue: "Work",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	YXuFuYjH_: {
		defaultValue: "14px",
		title: "Radius",
		type: ControlType.BorderRadius,
	},
	CfQsnK3E6: {
		defaultValue: {
			borderColor:
				'var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223)) /* {"name":"White/80"} */',
			borderStyle: "solid",
			borderWidth: 1,
		},
		title: "Border",
		type: ControlType.Border,
	},
	ALaEy4Ra3: {
		defaultValue:
			'var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19)) /* {"name":"Black"} */',
		title: "Hover BG",
		type: ControlType.Color,
	},
	d9a9Ooocv: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerhoEBqMEaI,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button/button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "o0l93dZIx",
};
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_default = ComponentWithRoot;
export { button_default as default };
