// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6d1ac80c6e7bce05 "Projeto Chacal", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Open' // Variant
 * hover?: Function // Hover
 * title?: string // Title
 * desc?: string // Desc
 * click?: Function // Click
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-XO7AUMAJ.js";
import { routes } from "./chunks/chunk-XLH7UDAO.js";

// virtual:accordian
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/g6FT7g4CEySKH9vtFXLL/mJxzTp9dI6JzKC2YZWcO/AxEeASfMc.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var enabledGestures = {
	KLC5OTNRR: {
		hover: true,
	},
};
var cycleOrder = ["KLC5OTNRR", "oboLd93ly"];
var serializationHash = "framer-DXQbZ";
var variantClassNames = {
	KLC5OTNRR: "framer-v-1ce8hsp",
	oboLd93ly: "framer-v-cab4qn",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.8,
	type: "spring",
};
var transition2 = {
	bounce: 0,
	delay: 0,
	duration: 0.2,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "KLC5OTNRR",
	Open: "oboLd93ly",
};
var getProps = ({ click, desc, height, hover, id, title, width, ...props }) => {
	return {
		...props,
		mSagMFOJe:
			desc ??
			props.mSagMFOJe ??
			"We specialize in website design, branding, motion graphics, and more to elevate your digital presence.",
		pcWhqXyF1: hover ?? props.pcWhqXyF1,
		ReZs6H67j:
			title ?? props.ReZs6H67j ?? "What services does Unfixed Studio offer?",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "KLC5OTNRR",
		vsogjJW_W: click ?? props.vsogjJW_W,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		pcWhqXyF1,
		ReZs6H67j,
		mSagMFOJe,
		vsogjJW_W,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "KLC5OTNRR",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1348joj = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (vsogjJW_W) {
			const res = await vsogjJW_W(...args);
			if (res === false) return false;
		}
	});
	const onMouseEnterigxzn6 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		if (pcWhqXyF1) {
			const res = await pcWhqXyF1(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "oboLd93ly") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							oboLd93ly: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1ce8hsp",
							className2,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Default"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"KLC5OTNRR"}
						onMouseEnter={onMouseEnterigxzn6}
						onTap={onTap1348joj}
						ref={ref ?? ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-dbae631d-d751-404b-ae6d-1639e29be314, rgb(84, 84, 84))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							backgroundColor:
								"var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(239, 238, 236))",
							...style,
						}}
						variants={{
							oboLd93ly: {
								"--border-bottom-width": "0px",
								backgroundColor:
									"var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19))",
							},
						}}
						{...addPropertyOverrides(
							{
								"KLC5OTNRR-hover": {
									"data-framer-name": void 0,
								},
								oboLd93ly: {
									"data-framer-name": "Open",
									onMouseEnter: void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1itr6y7"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"wTcQorJ19"}
						>
							<motion.div
								className={"framer-u7iw01"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"OAeZvWljf"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1mzn6bo"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"sFZBlw94W"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={ReZs6H67j}
									variants={{
										oboLd93ly: {
											"--extracted-r6o4lv":
												"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											oboLd93ly: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-q12std"}
															data-styles-preset={"nZjNjGRCH"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223)))",
															}}
														>
															{"What services does Unfixed Studio offer?"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-q12std"}
											data-styles-preset={"nZjNjGRCH"}
										>
											{"What services does Unfixed Studio offer?"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1sm65bi"}
								data-framer-name={"Plus"}
								layoutDependency={layoutDependency}
								layoutId={"JNmamUFn6"}
								style={{
									backgroundColor:
										"var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19))",
									borderBottomLeftRadius: 5,
									borderBottomRightRadius: 5,
									borderTopLeftRadius: 5,
									borderTopRightRadius: 5,
									rotate: 0,
								}}
								variants={{
									"KLC5OTNRR-hover": {
										rotate: 90,
									},
									oboLd93ly: {
										backgroundColor:
											"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
									},
								}}
							>
								<motion.div
									className={"framer-13nhyl7"}
									data-framer-name={"Icon"}
									layoutDependency={layoutDependency}
									layoutId={"iTNQs2hjH"}
									style={{
										rotate: 0,
									}}
									variants={{
										"KLC5OTNRR-hover": {
											rotate: 0,
										},
										oboLd93ly: {
											rotate: 45,
										},
									}}
								>
									<motion.div
										className={"framer-agznxh"}
										data-framer-name={"Line 2"}
										layoutDependency={layoutDependency}
										layoutId={"b6wRwHF8S"}
										style={{
											backgroundColor: "rgb(255, 255, 255)",
											rotate: 270,
										}}
										variants={{
											oboLd93ly: {
												backgroundColor:
													"var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19))",
											},
										}}
									/>
									<motion.div
										className={"framer-19bbana"}
										data-framer-name={"Line 1"}
										layoutDependency={layoutDependency}
										layoutId={"fwDR89pf1"}
										style={{
											backgroundColor: "rgb(255, 255, 255)",
										}}
										variants={{
											oboLd93ly: {
												backgroundColor:
													"var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19))",
											},
										}}
									/>
								</motion.div>
							</motion.div>
						</motion.div>
						{isDisplayed() && (
							<Transition value={transition1}>
								<motion.div
									className={"framer-ylmn5f"}
									data-framer-name={"Container"}
									layoutDependency={layoutDependency}
									layoutId={"iiq98vnIk"}
								>
									<motion.div
										className={"framer-1cc4z2b"}
										data-framer-name={"Title"}
										layoutDependency={layoutDependency}
										layoutId={"w9exMMpgV"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-18eec0v"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"bws3a9gLg"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-a94f824d-9740-42c5-b0f6-0397fd7c5912, rgb(158, 158, 158))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={mSagMFOJe}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-q12std"}
													data-styles-preset={"nZjNjGRCH"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-a94f824d-9740-42c5-b0f6-0397fd7c5912, rgb(158, 158, 158)))",
													}}
												>
													{
														"We specialize in website design, branding, motion graphics, and more to elevate your digital presence."
													}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
							</Transition>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-DXQbZ.framer-1022kr3, .framer-DXQbZ .framer-1022kr3 { display: block; }",
	".framer-DXQbZ.framer-1ce8hsp { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 8px 0px 0px; position: relative; width: 468px; }",
	".framer-DXQbZ .framer-1itr6y7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 14px 0px 14px 0px; position: relative; width: 100%; }",
	".framer-DXQbZ .framer-u7iw01 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-DXQbZ .framer-1mzn6bo, .framer-DXQbZ .framer-18eec0v { --framer-text-wrap-override: balance; -webkit-user-select: none; flex: 1 0 0px; height: auto; position: relative; user-select: none; width: 1px; }",
	".framer-DXQbZ .framer-1sm65bi { aspect-ratio: 1 / 1; cursor: pointer; flex: none; height: var(--framer-aspect-ratio-supported, 28px); overflow: hidden; position: relative; width: 28px; will-change: var(--framer-will-change-override, transform); }",
	".framer-DXQbZ .framer-13nhyl7 { flex: none; height: 12px; left: calc(50.00000000000002% - 12px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 12px / 2); width: 12px; }",
	".framer-DXQbZ .framer-agznxh, .framer-DXQbZ .framer-19bbana { bottom: 0px; flex: none; left: calc(50.00000000000002% - 2px / 2); overflow: hidden; position: absolute; top: 0px; width: 2px; }",
	".framer-DXQbZ .framer-ylmn5f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px 14px 14px 0px; position: relative; width: 100%; }",
	".framer-DXQbZ .framer-1cc4z2b { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-DXQbZ.framer-1ce8hsp, .framer-DXQbZ .framer-u7iw01, .framer-DXQbZ .framer-ylmn5f, .framer-DXQbZ .framer-1cc4z2b { gap: 0px; } .framer-DXQbZ.framer-1ce8hsp > * { margin: 0px; margin-bottom: calc(14px / 2); margin-top: calc(14px / 2); } .framer-DXQbZ.framer-1ce8hsp > :first-child { margin-top: 0px; } .framer-DXQbZ.framer-1ce8hsp > :last-child { margin-bottom: 0px; } .framer-DXQbZ .framer-u7iw01 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-DXQbZ .framer-u7iw01 > :first-child, .framer-DXQbZ .framer-ylmn5f > :first-child, .framer-DXQbZ .framer-1cc4z2b > :first-child { margin-left: 0px; } .framer-DXQbZ .framer-u7iw01 > :last-child, .framer-DXQbZ .framer-ylmn5f > :last-child, .framer-DXQbZ .framer-1cc4z2b > :last-child { margin-right: 0px; } .framer-DXQbZ .framer-ylmn5f > *, .framer-DXQbZ .framer-1cc4z2b > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } }",
	".framer-DXQbZ.framer-v-cab4qn.framer-1ce8hsp { gap: 0px; padding: 0px 18px 0px 18px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-DXQbZ.framer-v-cab4qn.framer-1ce8hsp { gap: 0px; } .framer-DXQbZ.framer-v-cab4qn.framer-1ce8hsp > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-DXQbZ.framer-v-cab4qn.framer-1ce8hsp > :first-child { margin-top: 0px; } .framer-DXQbZ.framer-v-cab4qn.framer-1ce8hsp > :last-child { margin-bottom: 0px; } }",
	".framer-DXQbZ.framer-v-1ce8hsp.hover.framer-1ce8hsp { padding: 0px; }",
	".framer-DXQbZ.framer-v-1ce8hsp.hover .framer-1itr6y7 { padding: 14px 10px 14px 10px; }",
	...css,
	'.framer-DXQbZ[data-border="true"]::after, .framer-DXQbZ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerAxEeASfMc = withCSS(Component, css2, "framer-DXQbZ");
var stdin_default = FramerAxEeASfMc;
FramerAxEeASfMc.displayName = "Accordian";
FramerAxEeASfMc.defaultProps = {
	height: 56,
	width: 468,
};
addPropertyControls(FramerAxEeASfMc, {
	variant: {
		options: ["KLC5OTNRR", "oboLd93ly"],
		optionTitles: ["Default", "Open"],
		title: "Variant",
		type: ControlType.Enum,
	},
	pcWhqXyF1: {
		title: "Hover",
		type: ControlType.EventHandler,
	},
	ReZs6H67j: {
		defaultValue: "What services does Unfixed Studio offer?",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	mSagMFOJe: {
		defaultValue:
			"We specialize in website design, branding, motion graphics, and more to elevate your digital presence.",
		displayTextArea: false,
		title: "Desc",
		type: ControlType.String,
	},
	vsogjJW_W: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerAxEeASfMc,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:accordian
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "KLC5OTNRR",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AccordianFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var accordian_default = ComponentWithRoot;
export { accordian_default as default };
