// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6d1ac80c6e7bce05 "Projeto Chacal", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Tablet' // Variant
 * title?: string // Title
 * date?: string // Date
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-XO7AUMAJ.js";
import { routes } from "./chunks/chunk-XLH7UDAO.js";

// virtual:blog-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/rFxJdCwtaG6MmXchJER8/QIvaqloGllXYfsZVX5Y6/xvT4C7hqo.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var enabledGestures = {
	DcQ1xBmIy: {
		hover: true,
	},
	izpG1zm1F: {
		hover: true,
	},
};
var cycleOrder = ["izpG1zm1F", "DcQ1xBmIy"];
var serializationHash = "framer-lnQ2d";
var variantClassNames = {
	DcQ1xBmIy: "framer-v-yd3pd8",
	izpG1zm1F: "framer-v-amwi5d",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.8,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "izpG1zm1F",
	Tablet: "DcQ1xBmIy",
};
var getProps = ({ date, height, id, image, title, width, ...props }) => {
	return {
		...props,
		AVVYUhd4G: date ?? props.AVVYUhd4G ?? "22 JAN",
		ki26uSOzS: image ??
			props.ki26uSOzS ?? {
				alt: "",
				src: "https://framerusercontent.com/images/ak3huUt2CL8kTQwiGctKwXcjeQ.png?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/ak3huUt2CL8kTQwiGctKwXcjeQ.png?scale-down-to=1024 771w,https://framerusercontent.com/images/ak3huUt2CL8kTQwiGctKwXcjeQ.png?scale-down-to=2048 1542w,https://framerusercontent.com/images/ak3huUt2CL8kTQwiGctKwXcjeQ.png 1856w",
			},
		MnKU3QLm7: title ?? props.MnKU3QLm7 ?? "Top 5 Web Design",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "izpG1zm1F",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		MnKU3QLm7,
		AVVYUhd4G,
		ki26uSOzS,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "izpG1zm1F",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-amwi5d",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"izpG1zm1F"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"DcQ1xBmIy-hover": {
									"data-framer-name": void 0,
								},
								"izpG1zm1F-hover": {
									"data-framer-name": void 0,
								},
								DcQ1xBmIy: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1gy19hl"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"vh5tS9n7T"}
							style={{
								scale: 1,
							}}
							variants={{
								"DcQ1xBmIy-hover": {
									scale: 1,
								},
								"izpG1zm1F-hover": {
									scale: 0.99,
								},
							}}
						>
							<motion.div
								className={"framer-1xrnus8"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"EePDQiKwI"}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												(0 +
													((componentViewport?.height || 388) - 0 - 478) / 2) +
												4 +
												0 +
												0,
										),
										pixelHeight: 2464,
										pixelWidth: 1856,
										sizes: `max(max(${componentViewport?.width || "100vw"}, 1px) - 8px, 1px)`,
										...toResponsiveImage(ki26uSOzS),
									}}
									className={"framer-1v04tpw"}
									layoutDependency={layoutDependency}
									layoutId={"aagnHru5G"}
									{...addPropertyOverrides(
										{
											DcQ1xBmIy: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(0 +
																((componentViewport?.height || 361) - 0 - 428) /
																	2) +
															4 +
															0 +
															0,
													),
													pixelHeight: 2464,
													pixelWidth: 1856,
													sizes: `max(max(${componentViewport?.width || "100vw"}, 1px) - 8px, 1px)`,
													...toResponsiveImage(ki26uSOzS),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
							<motion.div
								className={"framer-zm22dy"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"OgcYb18ag"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-b08x4v"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"vv5fZ_cVf"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={MnKU3QLm7}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-q12std"}
											data-styles-preset={"nZjNjGRCH"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19)))",
											}}
										>
											{"Top 5 Web Design"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-6tl1k5"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"XuqHUvDGK"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-dbae631d-d751-404b-ae6d-1639e29be314, rgb(84, 84, 84))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={AVVYUhd4G}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-q12std"}
											data-styles-preset={"nZjNjGRCH"}
											style={{
												"--framer-text-alignment": "right",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-dbae631d-d751-404b-ae6d-1639e29be314, rgb(84, 84, 84)))",
											}}
										>
											{"22 JAN"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-1v2aq0j"}
							data-framer-name={"Border"}
							layoutDependency={layoutDependency}
							layoutId={"PiBMmNBeh"}
							style={{
								mask: "linear-gradient(180deg, rgb(0, 0, 0) 40.54054054054054%, rgba(0, 0, 0, 0) 66.21621621621621%) add",
								WebkitMask:
									"linear-gradient(180deg, rgb(0, 0, 0) 40.54054054054054%, rgba(0, 0, 0, 0) 66.21621621621621%) add",
							}}
						>
							<motion.div
								className={"framer-6uvkp9"}
								data-framer-name={"TR"}
								layoutDependency={layoutDependency}
								layoutId={"XQz1XBe6F"}
							>
								<motion.div
									className={"framer-ggbi57"}
									data-framer-name={"Bottom"}
									layoutDependency={layoutDependency}
									layoutId={"Ag6hQAtOL"}
									style={{
										backgroundColor:
											"var(--token-dbae631d-d751-404b-ae6d-1639e29be314, rgb(84, 84, 84))",
									}}
								/>
								<motion.div
									className={"framer-qpa01a"}
									data-framer-name={"Top"}
									layoutDependency={layoutDependency}
									layoutId={"EWcKbmMJO"}
									style={{
										backgroundColor:
											"var(--token-dbae631d-d751-404b-ae6d-1639e29be314, rgb(84, 84, 84))",
									}}
								/>
							</motion.div>
							<motion.div
								className={"framer-s8ln9f"}
								data-framer-name={"TL"}
								layoutDependency={layoutDependency}
								layoutId={"uJ14jZi4X"}
							>
								<motion.div
									className={"framer-1dtdiav"}
									data-framer-name={"Bottom"}
									layoutDependency={layoutDependency}
									layoutId={"Pck7prPe4"}
									style={{
										backgroundColor:
											"var(--token-dbae631d-d751-404b-ae6d-1639e29be314, rgb(84, 84, 84))",
									}}
								/>
								<motion.div
									className={"framer-1gum0s4"}
									data-framer-name={"Top"}
									layoutDependency={layoutDependency}
									layoutId={"mAmUeoosQ"}
									style={{
										backgroundColor:
											"var(--token-dbae631d-d751-404b-ae6d-1639e29be314, rgb(84, 84, 84))",
									}}
								/>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-lnQ2d.framer-1hu9mvr, .framer-lnQ2d .framer-1hu9mvr { display: block; }",
	".framer-lnQ2d.framer-amwi5d { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 300px; }",
	".framer-lnQ2d .framer-1gy19hl { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 4px; position: relative; width: 1px; z-index: 2; }",
	".framer-lnQ2d .framer-1xrnus8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-lnQ2d .framer-1v04tpw { flex: 1 0 0px; height: 350px; overflow: visible; position: relative; width: 1px; }",
	".framer-lnQ2d .framer-zm22dy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 4; }",
	".framer-lnQ2d .framer-b08x4v, .framer-lnQ2d .framer-6tl1k5 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-lnQ2d .framer-1v2aq0j { flex: none; height: 101%; left: calc(50.00000000000002% - 100% / 2); overflow: visible; position: absolute; top: 0px; width: 100%; z-index: 0; }",
	".framer-lnQ2d .framer-6uvkp9 { flex: none; height: 11px; overflow: visible; position: absolute; right: 0px; top: 0px; width: 11px; }",
	".framer-lnQ2d .framer-ggbi57 { bottom: 3px; flex: none; overflow: visible; position: absolute; right: 0px; top: 0px; width: 1px; z-index: 1; }",
	".framer-lnQ2d .framer-qpa01a { flex: none; height: 1px; overflow: visible; position: absolute; right: 0px; top: 0px; width: 8px; z-index: 3; }",
	".framer-lnQ2d .framer-s8ln9f { flex: none; height: 11px; left: 0px; overflow: visible; position: absolute; top: 0px; width: 11px; }",
	".framer-lnQ2d .framer-1dtdiav { bottom: 3px; flex: none; left: 0px; overflow: visible; position: absolute; top: 0px; width: 1px; z-index: 1; }",
	".framer-lnQ2d .framer-1gum0s4 { flex: none; height: 1px; left: 0px; overflow: visible; position: absolute; right: 3px; top: 0px; z-index: 3; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-lnQ2d.framer-amwi5d, .framer-lnQ2d .framer-1gy19hl, .framer-lnQ2d .framer-1xrnus8, .framer-lnQ2d .framer-zm22dy { gap: 0px; } .framer-lnQ2d.framer-amwi5d > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-lnQ2d.framer-amwi5d > :first-child, .framer-lnQ2d .framer-1xrnus8 > :first-child, .framer-lnQ2d .framer-zm22dy > :first-child { margin-left: 0px; } .framer-lnQ2d.framer-amwi5d > :last-child, .framer-lnQ2d .framer-1xrnus8 > :last-child, .framer-lnQ2d .framer-zm22dy > :last-child { margin-right: 0px; } .framer-lnQ2d .framer-1gy19hl > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-lnQ2d .framer-1gy19hl > :first-child { margin-top: 0px; } .framer-lnQ2d .framer-1gy19hl > :last-child { margin-bottom: 0px; } .framer-lnQ2d .framer-1xrnus8 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-lnQ2d .framer-zm22dy > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } }",
	".framer-lnQ2d.framer-v-yd3pd8.framer-amwi5d { width: 250px; }",
	".framer-lnQ2d.framer-v-yd3pd8 .framer-1v04tpw { height: 300px; }",
	...css,
];
var FramerxvT4C7hqo = withCSS(Component, css2, "framer-lnQ2d");
var stdin_default = FramerxvT4C7hqo;
FramerxvT4C7hqo.displayName = "Blog Card";
FramerxvT4C7hqo.defaultProps = {
	height: 388,
	width: 300,
};
addPropertyControls(FramerxvT4C7hqo, {
	variant: {
		options: ["izpG1zm1F", "DcQ1xBmIy"],
		optionTitles: ["Default", "Tablet"],
		title: "Variant",
		type: ControlType.Enum,
	},
	MnKU3QLm7: {
		defaultValue: "Top 5 Web Design",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	AVVYUhd4G: {
		defaultValue: "22 JAN",
		displayTextArea: false,
		title: "Date",
		type: ControlType.String,
	},
	ki26uSOzS: {
		__defaultAssetReference:
			"data:framer/asset-reference,ak3huUt2CL8kTQwiGctKwXcjeQ.png?originalFilename=QmXVH6KsTS1GTVgPwrTbpCnS4PfEtSTTLyNCR8v6dV4DvH.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,ak3huUt2CL8kTQwiGctKwXcjeQ.png?originalFilename=QmXVH6KsTS1GTVgPwrTbpCnS4PfEtSTTLyNCR8v6dV4DvH.png&preferredSize=auto",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerxvT4C7hqo,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:blog-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "DcQ1xBmIy",
	xl: "izpG1zm1F",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BlogCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var blog_card_default = ComponentWithRoot;
export { blog_card_default as default };
