// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6d1ac80c6e7bce05 "Projeto Chacal", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * link?: string // Link
 * underline?: string // Underline
 * color?: string // Color
 * backgroundLayer?: string // Background Layer
 * invert?: number // Invert
 * blendingMode?: 'Normal' | 'Multiply' | 'Screen' | 'Overlay' | 'Darken' | 'Lighten' | 'Color Dodge' | 'Color Burn' | 'Hard Light' | 'Soft Light' | 'Difference' | 'Exclusion' | 'Hue' | 'Saturation' | 'Color' | 'Luminosity' // Blending Mode
 * newTab?: boolean // New Tab
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-XO7AUMAJ.js";
import { routes } from "./chunks/chunk-XLH7UDAO.js";

// virtual:button-underline
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/lcaKCAoYjI00YVGs6nhD/RlEHgSOwwNDqPRIN2ZjK/JfT45DPKP.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var enabledGestures = {
	NNydoJnfQ: {
		hover: true,
	},
};
var serializationHash = "framer-27tzJ";
var variantClassNames = {
	NNydoJnfQ: "framer-v-14ua6vi",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	bounce: 0,
	delay: 0,
	duration: 1.8,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableEnumMap = {
	"Color Burn": "color-burn",
	"Color Dodge": "color-dodge",
	"Hard Light": "hard-light",
	"Soft Light": "soft-light",
	Color: "color",
	Darken: "darken",
	Difference: "difference",
	Exclusion: "exclusion",
	Hue: "hue",
	Lighten: "lighten",
	Luminosity: "luminosity",
	Multiply: "multiply",
	Normal: "normal",
	Overlay: "overlay",
	Saturation: "saturation",
	Screen: "screen",
};
var getProps = ({
	backgroundLayer,
	blendingMode,
	color,
	height,
	id,
	invert,
	link,
	newTab,
	title,
	underline,
	width,
	...props
}) => {
	return {
		...props,
		AZYHIqVtf: invert ?? props.AZYHIqVtf ?? 100,
		Dm1HwYCcc:
			underline ??
			props.Dm1HwYCcc ??
			"var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19))",
		IyLekcjWz:
			backgroundLayer ??
			props.IyLekcjWz ??
			"var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(239, 238, 236))",
		kfXc9fuiw: link ?? props.kfXc9fuiw,
		QiMdeSOVx:
			color ??
			props.QiMdeSOVx ??
			"var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19))",
		SfChDKnP4: title ?? props.SfChDKnP4 ?? "Contact Me",
		vc_Z6vcgK:
			humanReadableEnumMap[blendingMode] ??
			blendingMode ??
			props.vc_Z6vcgK ??
			"difference",
		zhvClclQQ: newTab ?? props.zhvClclQQ,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		SfChDKnP4,
		kfXc9fuiw,
		Dm1HwYCcc,
		QiMdeSOVx,
		IyLekcjWz,
		AZYHIqVtf,
		vc_Z6vcgK,
		zhvClclQQ,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "NNydoJnfQ",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={kfXc9fuiw}
						nodeId={"NNydoJnfQ"}
						openInNewTab={zhvClclQQ}
						smoothScroll={true}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-14ua6vi", className2, classNames)} framer-l4alzb`}
							data-framer-name={"Default"}
							data-reset={"button"}
							layoutDependency={layoutDependency}
							layoutId={"NNydoJnfQ"}
							ref={ref ?? ref1}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"NNydoJnfQ-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1krayhn"}
								data-framer-name={"Button Underline"}
								layoutDependency={layoutDependency}
								layoutId={"ZDYNNrnjm"}
							>
								<motion.div
									className={"framer-mljxnr"}
									data-framer-name={"Title"}
									layoutDependency={layoutDependency}
									layoutId={"ZDYNNrnjmh3ixPNBdB"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-qrb3wk"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"GAYnKTSe2"}
										style={{
											"--extracted-r6o4lv":
												"var(--variable-reference-QiMdeSOVx-JfT45DPKP)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
											"--variable-reference-QiMdeSOVx-JfT45DPKP": QiMdeSOVx,
										}}
										text={SfChDKnP4}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-q12std"}
												data-styles-preset={"nZjNjGRCH"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--variable-reference-QiMdeSOVx-JfT45DPKP))",
												}}
											>
												{"Contact Me"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-14c6pai"}
									data-framer-name={"Icon"}
									layoutDependency={layoutDependency}
									layoutId={"jHji3DwFG"}
									style={{
										"--dhd4g1": vc_Z6vcgK,
										filter: `invert(${parseFloat(AZYHIqVtf) / 100})`,
										WebkitFilter: `invert(${parseFloat(AZYHIqVtf) / 100})`,
									}}
								>
									<motion.div
										className={"framer-1iv7tmo"}
										data-framer-name={"Bullet"}
										layoutDependency={layoutDependency}
										layoutId={"ZDYNNrnjmebLK8z7Qs"}
										style={{
											backgroundColor:
												"var(--token-7ab5faa8-d17b-41d2-8b42-49368cf2f4df, rgb(34, 39, 37))",
											borderBottomLeftRadius: 4,
											borderBottomRightRadius: 4,
											borderTopLeftRadius: 4,
											borderTopRightRadius: 4,
										}}
									>
										<motion.div
											className={"framer-a9dmul"}
											data-framer-name={"Icon"}
											layoutDependency={layoutDependency}
											layoutId={"ZDYNNrnjmuZDkkZ0qT"}
										>
											<motion.div
												className={"framer-8q8i3v"}
												data-framer-name={"Circle"}
												layoutDependency={layoutDependency}
												layoutId={"ZDYNNrnjma7kALew4G"}
												style={{
													backgroundColor:
														"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
													borderBottomLeftRadius: 9999,
													borderBottomRightRadius: 9999,
													borderTopLeftRadius: 9999,
													borderTopRightRadius: 9999,
												}}
											/>
										</motion.div>
									</motion.div>
								</motion.div>
								<Transition value={transition2}>
									<motion.div
										className={"framer-xbqw4c"}
										data-framer-name={"Underline White"}
										layoutDependency={layoutDependency}
										layoutId={"gIYlAtD92"}
										style={{
											backgroundColor: IyLekcjWz,
										}}
									/>
								</Transition>
								<motion.div
									className={"framer-tfs7mo"}
									data-framer-name={"Underline"}
									layoutDependency={layoutDependency}
									layoutId={"Mh59fEUrM"}
									style={{
										backgroundColor: Dm1HwYCcc,
									}}
								/>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-27tzJ.framer-l4alzb, .framer-27tzJ .framer-l4alzb { display: block; }",
	".framer-27tzJ.framer-14ua6vi { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-27tzJ .framer-1krayhn { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 4px 0px 4px 0px; position: relative; width: min-content; }",
	".framer-27tzJ .framer-mljxnr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-27tzJ .framer-qrb3wk { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-27tzJ .framer-14c6pai { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; mix-blend-mode: var(--dhd4g1); overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-27tzJ .framer-1iv7tmo { aspect-ratio: 1 / 1; cursor: pointer; flex: none; height: var(--framer-aspect-ratio-supported, 14px); overflow: hidden; position: relative; width: 14px; will-change: var(--framer-will-change-override, transform); }",
	".framer-27tzJ .framer-a9dmul { flex: none; height: 100%; left: 0px; overflow: visible; position: absolute; top: 0px; width: 100%; }",
	".framer-27tzJ .framer-8q8i3v { flex: none; height: 100%; left: calc(50.00000000000002% - min(5px, 100%) / 2); max-height: 5px; max-width: 5px; overflow: hidden; position: absolute; top: calc(50.00000000000002% - min(5px, 100%) / 2); width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-27tzJ .framer-xbqw4c { -webkit-tap-highlight-color: rgba(0, 0, 0, 0); bottom: 0px; flex: none; height: 1px; left: -92px; overflow: visible; position: absolute; width: 80px; z-index: 2; }",
	".framer-27tzJ .framer-tfs7mo { bottom: 0px; flex: none; height: 1px; left: calc(50.00000000000002% - 100% / 2); overflow: visible; position: absolute; width: 100%; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-27tzJ.framer-14ua6vi, .framer-27tzJ .framer-1krayhn, .framer-27tzJ .framer-mljxnr, .framer-27tzJ .framer-14c6pai { gap: 0px; } .framer-27tzJ.framer-14ua6vi > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-27tzJ.framer-14ua6vi > :first-child { margin-top: 0px; } .framer-27tzJ.framer-14ua6vi > :last-child { margin-bottom: 0px; } .framer-27tzJ .framer-1krayhn > * { margin: 0px; margin-left: calc(5px / 2); margin-right: calc(5px / 2); } .framer-27tzJ .framer-1krayhn > :first-child, .framer-27tzJ .framer-mljxnr > :first-child, .framer-27tzJ .framer-14c6pai > :first-child { margin-left: 0px; } .framer-27tzJ .framer-1krayhn > :last-child, .framer-27tzJ .framer-mljxnr > :last-child, .framer-27tzJ .framer-14c6pai > :last-child { margin-right: 0px; } .framer-27tzJ .framer-mljxnr > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-27tzJ .framer-14c6pai > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } }",
	".framer-27tzJ.framer-v-14ua6vi.hover .framer-a9dmul { height: 8px; width: 8px; }",
	".framer-27tzJ.framer-v-14ua6vi.hover .framer-8q8i3v { height: 8px; left: calc(50.00000000000002% - min(5px, 8px) / 2); top: calc(50.00000000000002% - min(5px, 8px) / 2); width: 8px; }",
	".framer-27tzJ.framer-v-14ua6vi.hover .framer-xbqw4c { left: 116px; right: -116px; width: unset; }",
	...css,
];
var FramerJfT45DPKP = withCSS(Component, css2, "framer-27tzJ");
var stdin_default = FramerJfT45DPKP;
FramerJfT45DPKP.displayName = "Button Underline";
FramerJfT45DPKP.defaultProps = {
	height: 30,
	width: 109,
};
addPropertyControls(FramerJfT45DPKP, {
	SfChDKnP4: {
		defaultValue: "Contact Me",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	kfXc9fuiw: {
		title: "Link",
		type: ControlType.Link,
	},
	Dm1HwYCcc: {
		defaultValue:
			'var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19)) /* {"name":"Black"} */',
		title: "Underline",
		type: ControlType.Color,
	},
	QiMdeSOVx: {
		defaultValue:
			'var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19)) /* {"name":"Black"} */',
		title: "Color",
		type: ControlType.Color,
	},
	IyLekcjWz: {
		defaultValue:
			'var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(239, 238, 236)) /* {"name":"BG"} */',
		title: "Background Layer",
		type: ControlType.Color,
	},
	AZYHIqVtf: {
		defaultValue: 100,
		title: "Invert",
		type: ControlType.Number,
	},
	vc_Z6vcgK: {
		defaultValue: "difference",
		options: [
			"normal",
			"multiply",
			"screen",
			"overlay",
			"darken",
			"lighten",
			"color-dodge",
			"color-burn",
			"hard-light",
			"soft-light",
			"difference",
			"exclusion",
			"hue",
			"saturation",
			"color",
			"luminosity",
		],
		optionTitles: [
			"Normal",
			"Multiply",
			"Screen",
			"Overlay",
			"Darken",
			"Lighten",
			"Color Dodge",
			"Color Burn",
			"Hard Light",
			"Soft Light",
			"Difference",
			"Exclusion",
			"Hue",
			"Saturation",
			"Color",
			"Luminosity",
		],
		title: "Blending Mode",
		type: ControlType.Enum,
	},
	zhvClclQQ: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType.Boolean,
	},
});
addFonts(
	FramerJfT45DPKP,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button-underline
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonUnderlineFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_underline_default = ComponentWithRoot;
export { button_underline_default as default };
