// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6d1ac80c6e7bce05 "Projeto Chacal", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Mobile' | 'Right' // Variant
 * title?: string // Title
 * shortDesc?: string // Short Desc
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * scrollSection?: undefined // Scroll Section
 * color?: string // Color
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-CT5FDIIK.js";
import { className, css, fonts } from "./chunks/chunk-XO7AUMAJ.js";
import { routes } from "./chunks/chunk-XLH7UDAO.js";

// virtual:card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/k0U5VDRpprENY4JxGHZh/rF1tfsMeNdN8Vf3ob5Ja/wdXaWv9fO.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var ImageWithFX = withFX(Image);
var enabledGestures = {
	iSP4L9k2l: {
		hover: true,
	},
	neg2rVWW6: {
		hover: true,
	},
};
var cycleOrder = ["neg2rVWW6", "zfCe6aqgl", "iSP4L9k2l"];
var serializationHash = "framer-LWdix";
var variantClassNames = {
	iSP4L9k2l: "framer-v-1kevqgq",
	neg2rVWW6: "framer-v-4ej8r1",
	zfCe6aqgl: "framer-v-1ns0uiq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.8,
	ease: [0.8, 0.2, 0, 1],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "neg2rVWW6",
	Mobile: "zfCe6aqgl",
	Right: "iSP4L9k2l",
};
var getProps = ({
	color,
	height,
	id,
	image,
	scrollSection,
	shortDesc,
	title,
	width,
	...props
}) => {
	return {
		...props,
		gWeawKDNt: image ??
			props.gWeawKDNt ?? {
				alt: "",
				src: "https://framerusercontent.com/images/S2tBgbeAO2o3wG9UoBgJ6MqEIic.png",
				srcSet:
					"https://framerusercontent.com/images/S2tBgbeAO2o3wG9UoBgJ6MqEIic.png?scale-down-to=1024 736w,https://framerusercontent.com/images/S2tBgbeAO2o3wG9UoBgJ6MqEIic.png 1472w",
			},
		ngAEURCMv: shortDesc ?? props.ngAEURCMv ?? "Design, Branding, UI/UX",
		rgzFTgwmf:
			color ??
			props.rgzFTgwmf ??
			"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
		sjI7Dwakw: title ?? props.sjI7Dwakw ?? "Prismatics Studio",
		Sz6SXL9SL: scrollSection ?? props.Sz6SXL9SL,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "neg2rVWW6",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		sjI7Dwakw,
		ngAEURCMv,
		gWeawKDNt,
		Sz6SXL9SL,
		rgzFTgwmf,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "neg2rVWW6",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-4ej8r1",
							className3,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"neg2rVWW6"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"iSP4L9k2l-hover": {
									"data-framer-name": void 0,
								},
								"neg2rVWW6-hover": {
									"data-framer-name": void 0,
								},
								iSP4L9k2l: {
									"data-framer-name": "Right",
								},
								zfCe6aqgl: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1x76qhi"}
							data-framer-name={"Text"}
							layoutDependency={layoutDependency}
							layoutId={"LSCrh6ZQA"}
						>
							<motion.div
								className={"framer-656iqi"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"qBJIUyYro"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1ijxij"}
									data-framer-name={"Title"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"lFMpg7xQ3"}
									style={{
										"--extracted-1w1cjl5":
											"var(--variable-reference-rgzFTgwmf-wdXaWv9fO)",
										"--variable-reference-rgzFTgwmf-wdXaWv9fO": rgzFTgwmf,
									}}
									text={sjI7Dwakw}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h6
											className={"framer-styles-preset-10ci24m"}
											data-styles-preset={"JZW8JfazT"}
											style={{
												"--framer-text-color":
													"var(--extracted-1w1cjl5, var(--variable-reference-rgzFTgwmf-wdXaWv9fO))",
											}}
										>
											{"Prismatics Studio"}
										</motion.h6>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-nl0y8r"}
									data-framer-name={"Bullet"}
									layoutDependency={layoutDependency}
									layoutId={"SZl1orQXr"}
									style={{
										opacity: 0,
										rotate: -30,
									}}
									variants={{
										"iSP4L9k2l-hover": {
											opacity: 1,
											rotate: 0,
										},
										"neg2rVWW6-hover": {
											opacity: 1,
											rotate: 0,
										},
									}}
								>
									<motion.div
										className={"framer-1ri48re"}
										data-framer-name={"Bullet"}
										layoutDependency={layoutDependency}
										layoutId={"kz0UcarPG"}
										style={{
											backgroundColor:
												"var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19))",
											borderBottomLeftRadius: 2,
											borderBottomRightRadius: 2,
											borderTopLeftRadius: 2,
											borderTopRightRadius: 2,
										}}
									>
										<motion.div
											className={"framer-1tnorqb"}
											data-framer-name={"Icon"}
											layoutDependency={layoutDependency}
											layoutId={"UoUf9dfrU"}
										>
											<motion.div
												className={"framer-ea96vn"}
												data-framer-name={"Circle"}
												layoutDependency={layoutDependency}
												layoutId={"wc2zNpnkc"}
												style={{
													backgroundColor:
														"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
													borderBottomLeftRadius: 9999,
													borderBottomRightRadius: 9999,
													borderTopLeftRadius: 9999,
													borderTopRightRadius: 9999,
												}}
											/>
										</motion.div>
									</motion.div>
								</motion.div>
							</motion.div>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-jy03ke"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"GUTmhiDFp"}
								style={{
									"--extracted-r6o4lv":
										"var(--variable-reference-rgzFTgwmf-wdXaWv9fO)",
									"--variable-reference-rgzFTgwmf-wdXaWv9fO": rgzFTgwmf,
								}}
								text={ngAEURCMv}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-q12std"}
										data-styles-preset={"nZjNjGRCH"}
										style={{
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--variable-reference-rgzFTgwmf-wdXaWv9fO))",
										}}
									>
										{"Design, Branding, UI/UX"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-1e21cf5"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"eD9Ue9Kea"}
						>
							<ImageWithFX
								__framer__styleTransformEffectEnabled={true}
								__framer__transformTargets={[
									{
										target: {
											opacity: 1,
											rotate: 0,
											rotateX: 0,
											rotateY: 0,
											scale: 1,
											skewX: 0,
											skewY: 0,
											x: 0,
											y: 0,
										},
									},
									{
										ref: Sz6SXL9SL,
										target: {
											opacity: 1,
											rotate: 0,
											rotateX: 0,
											rotateY: 0,
											scale: 1,
											skewX: 0,
											skewY: 0,
											x: 0,
											y: 800,
										},
									},
								]}
								__framer__transformTrigger={"onScrollTarget"}
								__framer__transformViewportThreshold={1}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											(0 * (((componentViewport?.height || 600) - 0 - 0) / 1) +
												0) +
											0 +
											-900,
									),
									pixelHeight: 2048,
									pixelWidth: 1472,
									sizes: `max(max((${componentViewport?.width || "100vw"} - 56px) / 4, 50px) * 2, 1px)`,
									...toResponsiveImage(gWeawKDNt),
								}}
								className={"framer-eljoqp"}
								data-border={true}
								layoutDependency={layoutDependency}
								layoutId={"BuuLRrTEO"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color": "rgba(0, 0, 0, 0.06)",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
								}}
								{...addPropertyOverrides(
									{
										zfCe6aqgl: {
											__framer__transformTargets: [
												{
													target: {
														opacity: 1,
														rotate: 0,
														rotateX: 0,
														rotateY: 0,
														scale: 1,
														skewX: 0,
														skewY: 0,
														x: 0,
														y: 0,
													},
												},
												{
													ref: Sz6SXL9SL,
													target: {
														opacity: 1,
														rotate: 0,
														rotateX: 0,
														rotateY: 0,
														scale: 1,
														skewX: 0,
														skewY: 0,
														x: 0,
														y: 150,
													},
												},
											],
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 0 + 0 + 0 + -150,
												),
												pixelHeight: 2048,
												pixelWidth: 1472,
												sizes: `max(${componentViewport?.width || "100vw"} - 28px, 1px)`,
												...toResponsiveImage(gWeawKDNt),
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-LWdix.framer-4q9k72, .framer-LWdix .framer-4q9k72 { display: block; }",
	".framer-LWdix.framer-4ej8r1 { cursor: pointer; display: grid; gap: 0px; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(4, minmax(50px, 1fr)); grid-template-rows: repeat(1, minmax(0, 1fr)); height: min-content; justify-content: center; overflow: hidden; padding: 0px 28px 0px 28px; position: relative; width: 1200px; }",
	".framer-LWdix .framer-1x76qhi { align-content: flex-start; align-items: flex-start; align-self: end; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 14px; grid-column: auto / span 2; height: min-content; justify-content: flex-end; justify-self: start; max-width: 1400px; padding: 0px 0px 45px 0px; position: relative; width: 100%; }",
	".framer-LWdix .framer-656iqi { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-LWdix .framer-1ijxij { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-LWdix .framer-nl0y8r { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 19px; justify-content: flex-end; left: -25px; overflow: visible; padding: 0px 4px 0px 4px; position: absolute; width: min-content; z-index: 1; }",
	".framer-LWdix .framer-1ri48re { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 12px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 12px; will-change: var(--framer-will-change-override, transform); }",
	".framer-LWdix .framer-1tnorqb { flex: none; height: 12px; overflow: visible; position: relative; width: 12px; }",
	".framer-LWdix .framer-ea96vn { flex: none; height: 8px; left: calc(50.00000000000002% - 8px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 8px / 2); width: 8px; will-change: var(--framer-will-change-override, transform); }",
	".framer-LWdix .framer-jy03ke { flex: none; height: auto; max-width: 80%; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-LWdix .framer-1e21cf5 { align-content: flex-end; align-items: flex-end; align-self: start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; grid-column: auto / span 2; height: 600px; justify-content: center; justify-self: start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-LWdix .framer-eljoqp { flex: 1 0 0px; height: 1500px; position: relative; width: 1px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-LWdix .framer-1x76qhi, .framer-LWdix .framer-656iqi, .framer-LWdix .framer-nl0y8r, .framer-LWdix .framer-1ri48re, .framer-LWdix .framer-1e21cf5 { gap: 0px; } .framer-LWdix .framer-1x76qhi > * { margin: 0px; margin-bottom: calc(14px / 2); margin-top: calc(14px / 2); } .framer-LWdix .framer-1x76qhi > :first-child, .framer-LWdix .framer-656iqi > :first-child { margin-top: 0px; } .framer-LWdix .framer-1x76qhi > :last-child, .framer-LWdix .framer-656iqi > :last-child { margin-bottom: 0px; } .framer-LWdix .framer-656iqi > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-LWdix .framer-nl0y8r > *, .framer-LWdix .framer-1ri48re > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-LWdix .framer-nl0y8r > :first-child, .framer-LWdix .framer-1ri48re > :first-child, .framer-LWdix .framer-1e21cf5 > :first-child { margin-left: 0px; } .framer-LWdix .framer-nl0y8r > :last-child, .framer-LWdix .framer-1ri48re > :last-child, .framer-LWdix .framer-1e21cf5 > :last-child { margin-right: 0px; } .framer-LWdix .framer-1e21cf5 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } }",
	".framer-LWdix.framer-v-1ns0uiq.framer-4ej8r1 { align-content: flex-end; align-items: flex-end; cursor: unset; display: flex; flex-direction: column; flex-wrap: wrap; gap: 14px; justify-content: flex-start; padding: 0px 14px 0px 14px; width: 390px; }",
	".framer-LWdix.framer-v-1ns0uiq .framer-1x76qhi { align-self: unset; gap: 4px; order: 1; padding: 0px; }",
	".framer-LWdix.framer-v-1ns0uiq .framer-jy03ke { max-width: 100%; }",
	".framer-LWdix.framer-v-1ns0uiq .framer-1e21cf5 { align-self: unset; height: 350px; order: 0; }",
	".framer-LWdix.framer-v-1ns0uiq .framer-eljoqp { height: 500px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-LWdix.framer-v-1ns0uiq.framer-4ej8r1, .framer-LWdix.framer-v-1ns0uiq .framer-1x76qhi { gap: 0px; } .framer-LWdix.framer-v-1ns0uiq.framer-4ej8r1 > * { margin: 0px; margin-bottom: calc(14px / 2); margin-top: calc(14px / 2); } .framer-LWdix.framer-v-1ns0uiq.framer-4ej8r1 > :first-child, .framer-LWdix.framer-v-1ns0uiq .framer-1x76qhi > :first-child { margin-top: 0px; } .framer-LWdix.framer-v-1ns0uiq.framer-4ej8r1 > :last-child, .framer-LWdix.framer-v-1ns0uiq .framer-1x76qhi > :last-child { margin-bottom: 0px; } .framer-LWdix.framer-v-1ns0uiq .framer-1x76qhi > * { margin: 0px; margin-bottom: calc(4px / 2); margin-top: calc(4px / 2); } }",
	".framer-LWdix.framer-v-1kevqgq .framer-1x76qhi { order: 1; padding: 0px 0px 45px 28px; }",
	".framer-LWdix.framer-v-1kevqgq .framer-1e21cf5 { order: 0; }",
	".framer-LWdix.framer-v-4ej8r1.hover .framer-656iqi, .framer-LWdix.framer-v-1kevqgq.hover .framer-656iqi { flex-direction: row; }",
	".framer-LWdix.framer-v-4ej8r1.hover .framer-1ijxij, .framer-LWdix.framer-v-1kevqgq.hover .framer-1ijxij { flex: 1 0 0px; order: 1; width: 1px; }",
	".framer-LWdix.framer-v-4ej8r1.hover .framer-nl0y8r, .framer-LWdix.framer-v-1kevqgq.hover .framer-nl0y8r { bottom: unset; left: unset; order: 0; position: relative; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-LWdix.framer-v-4ej8r1.hover .framer-656iqi { gap: 0px; } .framer-LWdix.framer-v-4ej8r1.hover .framer-656iqi > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-LWdix.framer-v-4ej8r1.hover .framer-656iqi > :first-child { margin-left: 0px; } .framer-LWdix.framer-v-4ej8r1.hover .framer-656iqi > :last-child { margin-right: 0px; } }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-LWdix.framer-v-1kevqgq.hover .framer-656iqi { gap: 0px; } .framer-LWdix.framer-v-1kevqgq.hover .framer-656iqi > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-LWdix.framer-v-1kevqgq.hover .framer-656iqi > :first-child { margin-left: 0px; } .framer-LWdix.framer-v-1kevqgq.hover .framer-656iqi > :last-child { margin-right: 0px; } }",
	...css2,
	...css,
	'.framer-LWdix[data-border="true"]::after, .framer-LWdix [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerwdXaWv9fO = withCSS(Component, css3, "framer-LWdix");
var stdin_default = FramerwdXaWv9fO;
FramerwdXaWv9fO.displayName = "Card";
FramerwdXaWv9fO.defaultProps = {
	height: 600,
	width: 1200,
};
addPropertyControls(FramerwdXaWv9fO, {
	variant: {
		options: ["neg2rVWW6", "zfCe6aqgl", "iSP4L9k2l"],
		optionTitles: ["Default", "Mobile", "Right"],
		title: "Variant",
		type: ControlType.Enum,
	},
	sjI7Dwakw: {
		defaultValue: "Prismatics Studio",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	ngAEURCMv: {
		defaultValue: "Design, Branding, UI/UX",
		displayTextArea: false,
		title: "Short Desc",
		type: ControlType.String,
	},
	gWeawKDNt: {
		__defaultAssetReference:
			"data:framer/asset-reference,S2tBgbeAO2o3wG9UoBgJ6MqEIic.png?originalFilename=QmUbTLkBMgpfmduvuUov6LTXpfdUDxduA6iULtgWqZudW6.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,S2tBgbeAO2o3wG9UoBgJ6MqEIic.png?originalFilename=QmUbTLkBMgpfmduvuUov6LTXpfdUDxduA6iULtgWqZudW6.png&preferredSize=auto",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	Sz6SXL9SL: {
		title: "Scroll Section",
		type: ControlType.ScrollSectionRef,
	},
	rgzFTgwmf: {
		defaultValue:
			'var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223)) /* {"name":"White/80"} */',
		title: "Color",
		type: ControlType.Color,
	},
});
addFonts(
	FramerwdXaWv9fO,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "zfCe6aqgl",
	xl: "neg2rVWW6",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var card_default = ComponentWithRoot;
export { card_default as default };
