// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6d1ac80c6e7bce05 "Projeto Chacal", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * color?: string // Color
 * checkColor ?: string // Check Color 
}} Props

 */
import { Icon, className, css, fonts } from "./chunks/chunk-U6HGDVS2.js";
import { routes } from "./chunks/chunk-XLH7UDAO.js";

// virtual:checklist
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/oK28wiXbMuVud5IOWr6c/tObKQKwiOeJW1VxYZ0eq/ymhOHV2jC.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var HeroFonts = getFonts(Icon);
var MotionDivWithFX = withFX(motion.div);
var RichTextWithFX = withFX(RichText);
var serializationHash = "framer-RGuP5";
var variantClassNames = {
	d6cf7QNha: "framer-v-10cw053",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition2 = {
	delay: 0,
	duration: 2,
	ease: [0.8, 0.2, 0, 1],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 5,
};
var animation3 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 5,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ checkColor, color, height, id, title, width, ...props }) => {
	return {
		...props,
		oEgcF7_Rd:
			color ??
			props.oEgcF7_Rd ??
			"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
		xCvjmPhd5:
			checkColor ??
			props.xCvjmPhd5 ??
			"var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19))",
		yGhsVlf69: title ?? props.yGhsVlf69 ?? "Custom design",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		yGhsVlf69,
		oEgcF7_Rd,
		xCvjmPhd5,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "d6cf7QNha",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-10cw053",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"d6cf7QNha"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
					>
						<MotionDivWithFX
							__framer__animate={{
								transition: transition2,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation}
							__framer__exit={animation1}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-rxligq"}
							data-framer-name={"Checklist"}
							layoutDependency={layoutDependency}
							layoutId={"quvhB4jTi"}
							style={{
								backgroundColor: oEgcF7_Rd,
								borderBottomLeftRadius: 12,
								borderBottomRightRadius: 12,
								borderTopLeftRadius: 12,
								borderTopRightRadius: 12,
							}}
						>
							<ComponentViewportProvider>
								<motion.div
									className={"framer-1vtvayf-container"}
									data-framer-name={"Checklist"}
									layoutDependency={layoutDependency}
									layoutId={"i6HqjOT2u-container"}
									name={"Checklist"}
								>
									<Icon
										color={xCvjmPhd5}
										height={"100%"}
										iconSearch={"Home"}
										iconSelection={"Check"}
										id={"i6HqjOT2u"}
										layoutId={"i6HqjOT2u"}
										mirrored={false}
										name={"Checklist"}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										width={"100%"}
									/>
								</motion.div>
							</ComponentViewportProvider>
						</MotionDivWithFX>
						<motion.div
							className={"framer-12uz3gi"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"L2yWW0w3G"}
						>
							<RichTextWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation2}
								__framer__exit={animation3}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-18bo8th"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Pc3tHZOTD"}
								style={{
									"--extracted-r6o4lv":
										"var(--variable-reference-oEgcF7_Rd-ymhOHV2jC)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									"--variable-reference-oEgcF7_Rd-ymhOHV2jC": oEgcF7_Rd,
								}}
								text={yGhsVlf69}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1ma3nx1"}
										data-styles-preset={"tB2h46m6z"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--variable-reference-oEgcF7_Rd-ymhOHV2jC))",
										}}
									>
										{"Custom design"}
									</motion.p>
								</React.Fragment>
							</RichTextWithFX>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-RGuP5.framer-fp6mx7, .framer-RGuP5 .framer-fp6mx7 { display: block; }",
	".framer-RGuP5.framer-10cw053 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 113px; }",
	".framer-RGuP5 .framer-rxligq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-RGuP5 .framer-1vtvayf-container { flex: none; height: 14px; position: relative; width: 14px; }",
	".framer-RGuP5 .framer-12uz3gi { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-RGuP5 .framer-18bo8th { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-RGuP5.framer-10cw053, .framer-RGuP5 .framer-rxligq, .framer-RGuP5 .framer-12uz3gi { gap: 0px; } .framer-RGuP5.framer-10cw053 > * { margin: 0px; margin-left: calc(4px / 2); margin-right: calc(4px / 2); } .framer-RGuP5.framer-10cw053 > :first-child, .framer-RGuP5 .framer-rxligq > :first-child, .framer-RGuP5 .framer-12uz3gi > :first-child { margin-left: 0px; } .framer-RGuP5.framer-10cw053 > :last-child, .framer-RGuP5 .framer-rxligq > :last-child, .framer-RGuP5 .framer-12uz3gi > :last-child { margin-right: 0px; } .framer-RGuP5 .framer-rxligq > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-RGuP5 .framer-12uz3gi > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } }",
	...css,
];
var FramerymhOHV2jC = withCSS(Component, css2, "framer-RGuP5");
var stdin_default = FramerymhOHV2jC;
FramerymhOHV2jC.displayName = "Checklist";
FramerymhOHV2jC.defaultProps = {
	height: 14,
	width: 113,
};
addPropertyControls(FramerymhOHV2jC, {
	yGhsVlf69: {
		defaultValue: "Custom design",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	oEgcF7_Rd: {
		defaultValue:
			"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
		title: "Color",
		type: ControlType.Color,
	},
	xCvjmPhd5: {
		defaultValue:
			'var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19)) /* {"name":"Black"} */',
		title: "Check Color ",
		type: ControlType.Color,
	},
});
addFonts(
	FramerymhOHV2jC,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...HeroFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:checklist
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ChecklistFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var checklist_default = ComponentWithRoot;
export { checklist_default as default };
