// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6d1ac80c6e7bce05 "Projeto Chacal", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Mobile' // Variant
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-XSHBFIPT.js";
import { stdin_default } from "./chunks/chunk-WL64HALP.js";
import { className, css, fonts } from "./chunks/chunk-TWQC6X2U.js";
import "./chunks/chunk-XO7AUMAJ.js";
import { routes } from "./chunks/chunk-XLH7UDAO.js";

// virtual:faq-content
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/r9a0S1Ayzy24ArOjtrYE/C4rRQeBwOEexvHYLVgrJ/by7EkoHbp.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	getFontsFromSharedStyle,
	ResolveLinks,
	RichText,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useRouter,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/bqvahDpqCPh6xdf1LhqS/l0gsfjvlb9yarMlMRTjN/x0ojEp2zn.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var AccordianFonts = getFonts(stdin_default2);
var cycleOrder = [
	"AxdgMy9Ls",
	"OFAkTatcC",
	"VqZIeDZKZ",
	"c9bDnx3OM",
	"NS3NaJ3IK",
	"Ztu2mn_gn",
];
var serializationHash = "framer-Q1CwP";
var variantClassNames = {
	AxdgMy9Ls: "framer-v-22f5e3",
	c9bDnx3OM: "framer-v-43deo2",
	NS3NaJ3IK: "framer-v-1se9vnd",
	OFAkTatcC: "framer-v-6q91uq",
	VqZIeDZKZ: "framer-v-1dyyvu6",
	Ztu2mn_gn: "framer-v-1khlvgj",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.8,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	1: "OFAkTatcC",
	2: "VqZIeDZKZ",
	3: "c9bDnx3OM",
	4: "NS3NaJ3IK",
	5: "Ztu2mn_gn",
	Default: "AxdgMy9Ls",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "AxdgMy9Ls",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "AxdgMy9Ls",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const vsogjJW_W205x63 = activeVariantCallback(async (...args) => {
		setVariant("OFAkTatcC");
	});
	const vsogjJW_Wwsrolz = activeVariantCallback(async (...args) => {
		setVariant("AxdgMy9Ls");
	});
	const vsogjJW_W8dxut5 = activeVariantCallback(async (...args) => {
		setVariant("VqZIeDZKZ");
	});
	const vsogjJW_Wy5qyx6 = activeVariantCallback(async (...args) => {
		setVariant("c9bDnx3OM");
	});
	const vsogjJW_Wmkwsjq = activeVariantCallback(async (...args) => {
		setVariant("NS3NaJ3IK");
	});
	const vsogjJW_W145c2f9 = activeVariantCallback(async (...args) => {
		setVariant("Ztu2mn_gn");
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-22f5e3",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"AxdgMy9Ls"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								c9bDnx3OM: {
									"data-framer-name": "3",
								},
								NS3NaJ3IK: {
									"data-framer-name": "4",
								},
								OFAkTatcC: {
									"data-framer-name": "1",
								},
								VqZIeDZKZ: {
									"data-framer-name": "2",
								},
								Ztu2mn_gn: {
									"data-framer-name": "5",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 320) - 0 - 320) / 2 + 0 + 0)
							}
							{...addPropertyOverrides(
								{
									c9bDnx3OM: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												0 +
												0),
									},
									NS3NaJ3IK: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												0 +
												0),
									},
									OFAkTatcC: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												0 +
												0),
									},
									VqZIeDZKZ: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												0 +
												0),
									},
									Ztu2mn_gn: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												0 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-52ltjw-container"}
								layoutDependency={layoutDependency}
								layoutId={"v8ArWo_hd-container"}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "v8ArWo_hd",
									layoutId: "v8ArWo_hd",
									mSagMFOJe:
										"We specialize in website design, branding, motion graphics, and more to elevate your digital presence.",
									ReZs6H67j: "What services does Unfixed Studio offer?",
									style: {
										width: "100%",
									},
									variant: "KLC5OTNRR",
									vsogjJW_W: vsogjJW_W205x63,
									width: "100%",
									...addPropertyOverrides(
										{
											OFAkTatcC: {
												variant: "oboLd93ly",
												vsogjJW_W: vsogjJW_Wwsrolz,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 320) - 0 - 320) / 2 + 64 + 0)
							}
							{...addPropertyOverrides(
								{
									c9bDnx3OM: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												64 +
												0),
									},
									NS3NaJ3IK: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												64 +
												0),
									},
									OFAkTatcC: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												64 +
												0),
									},
									VqZIeDZKZ: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												64 +
												0),
									},
									Ztu2mn_gn: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												64 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-e8r5jv-container"}
								layoutDependency={layoutDependency}
								layoutId={"SbLM2ooIe-container"}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "SbLM2ooIe",
									layoutId: "SbLM2ooIe",
									mSagMFOJe:
										"Project timelines vary, but most are completed within 2\u20136 weeks, depending on complexity.",
									ReZs6H67j: "How long does a typical project take?",
									style: {
										width: "100%",
									},
									variant: "KLC5OTNRR",
									vsogjJW_W: vsogjJW_W8dxut5,
									width: "100%",
									...addPropertyOverrides(
										{
											VqZIeDZKZ: {
												variant: "oboLd93ly",
												vsogjJW_W: vsogjJW_Wwsrolz,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 320) - 0 - 320) / 2 + 128 + 0)
							}
							{...addPropertyOverrides(
								{
									c9bDnx3OM: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												128 +
												0),
									},
									NS3NaJ3IK: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												128 +
												0),
									},
									OFAkTatcC: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												128 +
												0),
									},
									VqZIeDZKZ: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												128 +
												0),
									},
									Ztu2mn_gn: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												128 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-ycreqh-container"}
								layoutDependency={layoutDependency}
								layoutId={"PvwTzZ7jU-container"}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "PvwTzZ7jU",
									layoutId: "PvwTzZ7jU",
									mSagMFOJe:
										"Yes, we tailor all our services to meet your unique business goals and requirements.",
									ReZs6H67j: "Do you offer custom solutions?",
									style: {
										width: "100%",
									},
									variant: "KLC5OTNRR",
									vsogjJW_W: vsogjJW_Wy5qyx6,
									width: "100%",
									...addPropertyOverrides(
										{
											c9bDnx3OM: {
												variant: "oboLd93ly",
												vsogjJW_W: vsogjJW_Wwsrolz,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 320) - 0 - 320) / 2 + 192 + 0)
							}
							{...addPropertyOverrides(
								{
									c9bDnx3OM: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												192 +
												0),
									},
									NS3NaJ3IK: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												192 +
												0),
									},
									OFAkTatcC: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												192 +
												0),
									},
									VqZIeDZKZ: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												192 +
												0),
									},
									Ztu2mn_gn: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												192 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-17fjjc-container"}
								layoutDependency={layoutDependency}
								layoutId={"YMhpB5LGe-container"}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "YMhpB5LGe",
									layoutId: "YMhpB5LGe",
									mSagMFOJe:
										"We work with a variety of industries, including tech, e-commerce, entertainment, and startups.",
									ReZs6H67j: "What industries do you work with?",
									style: {
										width: "100%",
									},
									variant: "KLC5OTNRR",
									vsogjJW_W: vsogjJW_Wmkwsjq,
									width: "100%",
									...addPropertyOverrides(
										{
											NS3NaJ3IK: {
												variant: "oboLd93ly",
												vsogjJW_W: vsogjJW_Wwsrolz,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 320) - 0 - 320) / 2 + 256 + 0)
							}
							{...addPropertyOverrides(
								{
									c9bDnx3OM: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												256 +
												0),
									},
									NS3NaJ3IK: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												256 +
												0),
									},
									OFAkTatcC: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												256 +
												0),
									},
									VqZIeDZKZ: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												256 +
												0),
									},
									Ztu2mn_gn: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												256 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1t71sg4-container"}
								layoutDependency={layoutDependency}
								layoutId={"zliAwhlVD-container"}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "zliAwhlVD",
									layoutId: "zliAwhlVD",
									mSagMFOJe:
										"Our pricing is transparent, with flexible plans designed to fit different budgets and needs.",
									ReZs6H67j: "What is your pricing model?",
									style: {
										width: "100%",
									},
									variant: "KLC5OTNRR",
									vsogjJW_W: vsogjJW_W145c2f9,
									width: "100%",
									...addPropertyOverrides(
										{
											Ztu2mn_gn: {
												variant: "oboLd93ly",
												vsogjJW_W: vsogjJW_Wwsrolz,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Q1CwP.framer-1l65fs5, .framer-Q1CwP .framer-1l65fs5 { display: block; }",
	".framer-Q1CwP.framer-22f5e3 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; padding: 0px; position: relative; width: 468px; }",
	".framer-Q1CwP .framer-52ltjw-container, .framer-Q1CwP .framer-e8r5jv-container, .framer-Q1CwP .framer-ycreqh-container, .framer-Q1CwP .framer-17fjjc-container, .framer-Q1CwP .framer-1t71sg4-container { flex: none; height: auto; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Q1CwP.framer-22f5e3 { gap: 0px; } .framer-Q1CwP.framer-22f5e3 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-Q1CwP.framer-22f5e3 > :first-child { margin-top: 0px; } .framer-Q1CwP.framer-22f5e3 > :last-child { margin-bottom: 0px; } }",
];
var Framerx0ojEp2zn = withCSS(Component, css2, "framer-Q1CwP");
var stdin_default3 = Framerx0ojEp2zn;
Framerx0ojEp2zn.displayName = "FAQ";
Framerx0ojEp2zn.defaultProps = {
	height: 320,
	width: 468,
};
addPropertyControls(Framerx0ojEp2zn, {
	variant: {
		options: [
			"AxdgMy9Ls",
			"OFAkTatcC",
			"VqZIeDZKZ",
			"c9bDnx3OM",
			"NS3NaJ3IK",
			"Ztu2mn_gn",
		],
		optionTitles: ["Default", "1", "2", "3", "4", "5"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerx0ojEp2zn,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...AccordianFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/r9a0S1Ayzy24ArOjtrYE/C4rRQeBwOEexvHYLVgrJ/by7EkoHbp.js
var RichTextWithFX = withFX(RichText);
var ButtonUnderlineFonts = getFonts2(stdin_default);
var FAQFonts = getFonts2(stdin_default3);
var cycleOrder2 = ["Wd0HFM7r5", "eSc6b21DS"];
var serializationHash2 = "framer-Xbd82";
var variantClassNames2 = {
	eSc6b21DS: "framer-v-s0pnkz",
	Wd0HFM7r5: "framer-v-3ewzv5",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 40,
};
var transition2 = {
	delay: 0,
	duration: 1.5,
	ease: [0.8, 0.2, 0, 1],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 40,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 20,
};
var animation3 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 20,
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	Default: "Wd0HFM7r5",
	Mobile: "eSc6b21DS",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "Wd0HFM7r5",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "Wd0HFM7r5",
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const ref1 = React2.useRef(null);
	const router = useRouter();
	const defaultLayoutId = React2.useId();
	const componentViewport = useComponentViewport2();
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-3ewzv5",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"Wd0HFM7r5"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								eSc6b21DS: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-6jfsj3"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"K_yBmDWbp"}
						>
							<motion2.div
								className={"framer-wxr7cq"}
								data-framer-name={"Text"}
								layoutDependency={layoutDependency}
								layoutId={"r5J6ZrIGi"}
							>
								<motion2.div
									className={"framer-1gkzldv"}
									data-framer-name={"Split"}
									layoutDependency={layoutDependency}
									layoutId={"JK4NFV1PY"}
								>
									<RichTextWithFX
										__framer__animate={{
											transition: transition2,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__exit={animation1}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__fromCanvasComponent={true}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-gdod3i"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"uWaFGPswD"}
										style={{
											"--extracted-a0htzi":
												"var(--token-7ab5faa8-d17b-41d2-8b42-49368cf2f4df, rgb(34, 39, 37))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
										{...addPropertyOverrides2(
											{
												eSc6b21DS: {
													__framer__enter: animation2,
													__framer__exit: animation3,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React2.Fragment>
											<motion2.h3
												className={"framer-styles-preset-quploe"}
												data-styles-preset={"ksrCBwsI2"}
												style={{
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-a0htzi, var(--token-7ab5faa8-d17b-41d2-8b42-49368cf2f4df, rgb(34, 39, 37)))",
												}}
											>
												{"CAN'T  SPOT"}
											</motion2.h3>
										</React2.Fragment>
									</RichTextWithFX>
								</motion2.div>
								<motion2.div
									className={"framer-771n0p"}
									data-framer-name={"Split"}
									layoutDependency={layoutDependency}
									layoutId={"TSmFg3JdM"}
								>
									<RichTextWithFX
										__framer__animate={{
											transition: transition2,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation}
										__framer__exit={animation1}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__fromCanvasComponent={true}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-z8p1pn"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"sq1TGdebo"}
										style={{
											"--extracted-a0htzi":
												"var(--token-7ab5faa8-d17b-41d2-8b42-49368cf2f4df, rgb(34, 39, 37))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
										{...addPropertyOverrides2(
											{
												eSc6b21DS: {
													__framer__enter: animation2,
													__framer__exit: animation3,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React2.Fragment>
											<motion2.h3
												className={"framer-styles-preset-quploe"}
												data-styles-preset={"ksrCBwsI2"}
												style={{
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-a0htzi, var(--token-7ab5faa8-d17b-41d2-8b42-49368cf2f4df, rgb(34, 39, 37)))",
												}}
											>
												{"YOUR QUERY?"}
											</motion2.h3>
										</React2.Fragment>
									</RichTextWithFX>
								</motion2.div>
							</motion2.div>
							<ResolveLinks
								links={[
									{
										href: {
											webPageId: "iefCN0Uvo",
										},
										implicitPathVariables: void 0,
									},
									{
										href: {
											webPageId: "iefCN0Uvo",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks) => (
									<ComponentViewportProvider2
										height={30}
										y={(componentViewport?.y || 0) + 0 + 0 + 0 + 136}
										{...addPropertyOverrides2(
											{
												eSc6b21DS: {
													y: (componentViewport?.y || 0) + 0 + 0 + 0 + 126,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<motion2.div
											className={"framer-1mummt5-container"}
											layoutDependency={layoutDependency}
											layoutId={"oPy3o0kck-container"}
										>
											{_jsx2(stdin_default, {
												AZYHIqVtf: 0,
												Dm1HwYCcc:
													"var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19))",
												height: "100%",
												id: "oPy3o0kck",
												IyLekcjWz:
													"var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(239, 238, 236))",
												kfXc9fuiw: resolvedLinks[0],
												layoutId: "oPy3o0kck",
												QiMdeSOVx:
													"var(--token-dcb5abee-f4cc-4336-9800-a1eb8a5b9414, rgb(21, 21, 19))",
												SfChDKnP4: "CONTACT",
												vc_Z6vcgK: "difference",
												width: "100%",
												...addPropertyOverrides2(
													{
														eSc6b21DS: {
															kfXc9fuiw: resolvedLinks[1],
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</motion2.div>
									</ComponentViewportProvider2>
								)}
							</ResolveLinks>
						</motion2.div>
						<motion2.div
							className={"framer-1kcgdaw"}
							data-framer-name={"FAQ"}
							layoutDependency={layoutDependency}
							layoutId={"QM7WLkQrv"}
						>
							<ComponentViewportProvider2
								height={320}
								width={`calc(max((${componentViewport?.width || "100vw"} - 42px) / 4, 50px) * 2 + 14px)`}
								y={(componentViewport?.y || 0) + 0 + 0 + 0 + 0}
								{...addPropertyOverrides2(
									{
										eSc6b21DS: {
											width: `calc(max((${componentViewport?.width || "100vw"} - 24px) / 2, 50px) * 2 + 24px)`,
											y: (componentViewport?.y || 0) + 0 + 180 + 0 + 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<motion2.div
									className={"framer-1snq1ww-container"}
									layoutDependency={layoutDependency}
									layoutId={"SVeSy9cm9-container"}
								>
									{_jsx2(stdin_default3, {
										height: "100%",
										id: "SVeSy9cm9",
										layoutId: "SVeSy9cm9",
										style: {
											width: "100%",
										},
										variant: "AxdgMy9Ls",
										width: "100%",
									})}
								</motion2.div>
							</ComponentViewportProvider2>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Xbd82.framer-lzp9hy, .framer-Xbd82 .framer-lzp9hy { display: block; }",
	".framer-Xbd82.framer-3ewzv5 { display: grid; gap: 14px; grid-auto-rows: min-content; grid-template-columns: repeat(4, minmax(50px, 1fr)); grid-template-rows: repeat(1, min-content); height: min-content; justify-content: center; max-width: 1400px; overflow: visible; padding: 0px; position: relative; width: 1144px; }",
	".framer-Xbd82 .framer-6jfsj3 { align-content: flex-start; align-items: flex-start; align-self: start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; grid-column: auto / span 2; height: 1fr; justify-content: flex-start; justify-self: start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-Xbd82 .framer-wxr7cq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-Xbd82 .framer-1gkzldv, .framer-Xbd82 .framer-771n0p { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-Xbd82 .framer-gdod3i, .framer-Xbd82 .framer-z8p1pn { --framer-text-wrap-override: balance; flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-Xbd82 .framer-1mummt5-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-Xbd82 .framer-1kcgdaw { align-content: flex-start; align-items: flex-start; align-self: start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; grid-column: auto / span 2; height: auto; justify-content: center; justify-self: end; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-Xbd82 .framer-1snq1ww-container { flex: none; height: auto; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Xbd82 .framer-6jfsj3, .framer-Xbd82 .framer-wxr7cq, .framer-Xbd82 .framer-1gkzldv, .framer-Xbd82 .framer-771n0p, .framer-Xbd82 .framer-1kcgdaw { gap: 0px; } .framer-Xbd82 .framer-6jfsj3 > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-Xbd82 .framer-6jfsj3 > :first-child, .framer-Xbd82 .framer-wxr7cq > :first-child, .framer-Xbd82 .framer-1kcgdaw > :first-child { margin-top: 0px; } .framer-Xbd82 .framer-6jfsj3 > :last-child, .framer-Xbd82 .framer-wxr7cq > :last-child, .framer-Xbd82 .framer-1kcgdaw > :last-child { margin-bottom: 0px; } .framer-Xbd82 .framer-wxr7cq > *, .framer-Xbd82 .framer-1kcgdaw > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-Xbd82 .framer-1gkzldv > *, .framer-Xbd82 .framer-771n0p > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-Xbd82 .framer-1gkzldv > :first-child, .framer-Xbd82 .framer-771n0p > :first-child { margin-left: 0px; } .framer-Xbd82 .framer-1gkzldv > :last-child, .framer-Xbd82 .framer-771n0p > :last-child { margin-right: 0px; } }",
	".framer-Xbd82.framer-v-s0pnkz.framer-3ewzv5 { gap: 24px; grid-template-columns: repeat(2, minmax(50px, 1fr)); }",
	".framer-Xbd82.framer-v-s0pnkz .framer-6jfsj3 { gap: 14px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Xbd82.framer-v-s0pnkz.framer-3ewzv5, .framer-Xbd82.framer-v-s0pnkz .framer-6jfsj3 { gap: 0px; } .framer-Xbd82.framer-v-s0pnkz.framer-3ewzv5 > *, .framer-Xbd82.framer-v-s0pnkz.framer-3ewzv5 > :first-child, .framer-Xbd82.framer-v-s0pnkz.framer-3ewzv5 > :last-child { margin: 0px; } .framer-Xbd82.framer-v-s0pnkz .framer-6jfsj3 > * { margin: 0px; margin-bottom: calc(14px / 2); margin-top: calc(14px / 2); } .framer-Xbd82.framer-v-s0pnkz .framer-6jfsj3 > :first-child { margin-top: 0px; } .framer-Xbd82.framer-v-s0pnkz .framer-6jfsj3 > :last-child { margin-bottom: 0px; } }",
	...css,
];
var Framerby7EkoHbp = withCSS2(Component2, css3, "framer-Xbd82");
var stdin_default4 = Framerby7EkoHbp;
Framerby7EkoHbp.displayName = "FAQ Content";
Framerby7EkoHbp.defaultProps = {
	height: 280,
	width: 1144,
};
addPropertyControls2(Framerby7EkoHbp, {
	variant: {
		options: ["Wd0HFM7r5", "eSc6b21DS"],
		optionTitles: ["Default", "Mobile"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	Framerby7EkoHbp,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonUnderlineFonts,
		...FAQFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-content
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "eSc6b21DS",
	xl: "Wd0HFM7r5",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqContentFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var faq_content_default = ComponentWithRoot;
export { faq_content_default as default };
