// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6d1ac80c6e7bce05 "Projeto Chacal", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | '1' | '2' | '3' | '4' | '5' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-XSHBFIPT.js";
import "./chunks/chunk-XO7AUMAJ.js";
import { routes } from "./chunks/chunk-XLH7UDAO.js";

// virtual:faq
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/wOOesYU7TZRlRuUfhWwT/XSpKnaPnmpKoy6zL9yrc/x0ojEp2zn.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var AccordianFonts = getFonts(stdin_default);
var cycleOrder = [
	"AxdgMy9Ls",
	"OFAkTatcC",
	"VqZIeDZKZ",
	"c9bDnx3OM",
	"NS3NaJ3IK",
	"Ztu2mn_gn",
];
var serializationHash = "framer-Q1CwP";
var variantClassNames = {
	AxdgMy9Ls: "framer-v-22f5e3",
	c9bDnx3OM: "framer-v-43deo2",
	NS3NaJ3IK: "framer-v-1se9vnd",
	OFAkTatcC: "framer-v-6q91uq",
	VqZIeDZKZ: "framer-v-1dyyvu6",
	Ztu2mn_gn: "framer-v-1khlvgj",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.8,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	1: "OFAkTatcC",
	2: "VqZIeDZKZ",
	3: "c9bDnx3OM",
	4: "NS3NaJ3IK",
	5: "Ztu2mn_gn",
	Default: "AxdgMy9Ls",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "AxdgMy9Ls",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "AxdgMy9Ls",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const vsogjJW_W205x63 = activeVariantCallback(async (...args) => {
		setVariant("OFAkTatcC");
	});
	const vsogjJW_Wwsrolz = activeVariantCallback(async (...args) => {
		setVariant("AxdgMy9Ls");
	});
	const vsogjJW_W8dxut5 = activeVariantCallback(async (...args) => {
		setVariant("VqZIeDZKZ");
	});
	const vsogjJW_Wy5qyx6 = activeVariantCallback(async (...args) => {
		setVariant("c9bDnx3OM");
	});
	const vsogjJW_Wmkwsjq = activeVariantCallback(async (...args) => {
		setVariant("NS3NaJ3IK");
	});
	const vsogjJW_W145c2f9 = activeVariantCallback(async (...args) => {
		setVariant("Ztu2mn_gn");
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-22f5e3",
							className,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"AxdgMy9Ls"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								c9bDnx3OM: {
									"data-framer-name": "3",
								},
								NS3NaJ3IK: {
									"data-framer-name": "4",
								},
								OFAkTatcC: {
									"data-framer-name": "1",
								},
								VqZIeDZKZ: {
									"data-framer-name": "2",
								},
								Ztu2mn_gn: {
									"data-framer-name": "5",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 320) - 0 - 320) / 2 + 0 + 0)
							}
							{...addPropertyOverrides(
								{
									c9bDnx3OM: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												0 +
												0),
									},
									NS3NaJ3IK: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												0 +
												0),
									},
									OFAkTatcC: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												0 +
												0),
									},
									VqZIeDZKZ: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												0 +
												0),
									},
									Ztu2mn_gn: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												0 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-52ltjw-container"}
								layoutDependency={layoutDependency}
								layoutId={"v8ArWo_hd-container"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "v8ArWo_hd",
									layoutId: "v8ArWo_hd",
									mSagMFOJe:
										"We specialize in website design, branding, motion graphics, and more to elevate your digital presence.",
									ReZs6H67j: "What services does Unfixed Studio offer?",
									style: {
										width: "100%",
									},
									variant: "KLC5OTNRR",
									vsogjJW_W: vsogjJW_W205x63,
									width: "100%",
									...addPropertyOverrides(
										{
											OFAkTatcC: {
												variant: "oboLd93ly",
												vsogjJW_W: vsogjJW_Wwsrolz,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 320) - 0 - 320) / 2 + 64 + 0)
							}
							{...addPropertyOverrides(
								{
									c9bDnx3OM: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												64 +
												0),
									},
									NS3NaJ3IK: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												64 +
												0),
									},
									OFAkTatcC: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												64 +
												0),
									},
									VqZIeDZKZ: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												64 +
												0),
									},
									Ztu2mn_gn: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												64 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-e8r5jv-container"}
								layoutDependency={layoutDependency}
								layoutId={"SbLM2ooIe-container"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "SbLM2ooIe",
									layoutId: "SbLM2ooIe",
									mSagMFOJe:
										"Project timelines vary, but most are completed within 2\u20136 weeks, depending on complexity.",
									ReZs6H67j: "How long does a typical project take?",
									style: {
										width: "100%",
									},
									variant: "KLC5OTNRR",
									vsogjJW_W: vsogjJW_W8dxut5,
									width: "100%",
									...addPropertyOverrides(
										{
											VqZIeDZKZ: {
												variant: "oboLd93ly",
												vsogjJW_W: vsogjJW_Wwsrolz,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 320) - 0 - 320) / 2 + 128 + 0)
							}
							{...addPropertyOverrides(
								{
									c9bDnx3OM: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												128 +
												0),
									},
									NS3NaJ3IK: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												128 +
												0),
									},
									OFAkTatcC: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												128 +
												0),
									},
									VqZIeDZKZ: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												128 +
												0),
									},
									Ztu2mn_gn: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												128 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-ycreqh-container"}
								layoutDependency={layoutDependency}
								layoutId={"PvwTzZ7jU-container"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "PvwTzZ7jU",
									layoutId: "PvwTzZ7jU",
									mSagMFOJe:
										"Yes, we tailor all our services to meet your unique business goals and requirements.",
									ReZs6H67j: "Do you offer custom solutions?",
									style: {
										width: "100%",
									},
									variant: "KLC5OTNRR",
									vsogjJW_W: vsogjJW_Wy5qyx6,
									width: "100%",
									...addPropertyOverrides(
										{
											c9bDnx3OM: {
												variant: "oboLd93ly",
												vsogjJW_W: vsogjJW_Wwsrolz,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 320) - 0 - 320) / 2 + 192 + 0)
							}
							{...addPropertyOverrides(
								{
									c9bDnx3OM: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												192 +
												0),
									},
									NS3NaJ3IK: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												192 +
												0),
									},
									OFAkTatcC: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												192 +
												0),
									},
									VqZIeDZKZ: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												192 +
												0),
									},
									Ztu2mn_gn: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												192 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-17fjjc-container"}
								layoutDependency={layoutDependency}
								layoutId={"YMhpB5LGe-container"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "YMhpB5LGe",
									layoutId: "YMhpB5LGe",
									mSagMFOJe:
										"We work with a variety of industries, including tech, e-commerce, entertainment, and startups.",
									ReZs6H67j: "What industries do you work with?",
									style: {
										width: "100%",
									},
									variant: "KLC5OTNRR",
									vsogjJW_W: vsogjJW_Wmkwsjq,
									width: "100%",
									...addPropertyOverrides(
										{
											NS3NaJ3IK: {
												variant: "oboLd93ly",
												vsogjJW_W: vsogjJW_Wwsrolz,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={64}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 320) - 0 - 320) / 2 + 256 + 0)
							}
							{...addPropertyOverrides(
								{
									c9bDnx3OM: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												256 +
												0),
									},
									NS3NaJ3IK: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												256 +
												0),
									},
									OFAkTatcC: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												256 +
												0),
									},
									VqZIeDZKZ: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 372) - 0 - 320) / 2 +
												256 +
												0),
									},
									Ztu2mn_gn: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 320) / 2 +
												256 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1t71sg4-container"}
								layoutDependency={layoutDependency}
								layoutId={"zliAwhlVD-container"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "zliAwhlVD",
									layoutId: "zliAwhlVD",
									mSagMFOJe:
										"Our pricing is transparent, with flexible plans designed to fit different budgets and needs.",
									ReZs6H67j: "What is your pricing model?",
									style: {
										width: "100%",
									},
									variant: "KLC5OTNRR",
									vsogjJW_W: vsogjJW_W145c2f9,
									width: "100%",
									...addPropertyOverrides(
										{
											Ztu2mn_gn: {
												variant: "oboLd93ly",
												vsogjJW_W: vsogjJW_Wwsrolz,
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Q1CwP.framer-1l65fs5, .framer-Q1CwP .framer-1l65fs5 { display: block; }",
	".framer-Q1CwP.framer-22f5e3 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; padding: 0px; position: relative; width: 468px; }",
	".framer-Q1CwP .framer-52ltjw-container, .framer-Q1CwP .framer-e8r5jv-container, .framer-Q1CwP .framer-ycreqh-container, .framer-Q1CwP .framer-17fjjc-container, .framer-Q1CwP .framer-1t71sg4-container { flex: none; height: auto; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Q1CwP.framer-22f5e3 { gap: 0px; } .framer-Q1CwP.framer-22f5e3 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-Q1CwP.framer-22f5e3 > :first-child { margin-top: 0px; } .framer-Q1CwP.framer-22f5e3 > :last-child { margin-bottom: 0px; } }",
];
var Framerx0ojEp2zn = withCSS(Component, css, "framer-Q1CwP");
var stdin_default2 = Framerx0ojEp2zn;
Framerx0ojEp2zn.displayName = "FAQ";
Framerx0ojEp2zn.defaultProps = {
	height: 320,
	width: 468,
};
addPropertyControls(Framerx0ojEp2zn, {
	variant: {
		options: [
			"AxdgMy9Ls",
			"OFAkTatcC",
			"VqZIeDZKZ",
			"c9bDnx3OM",
			"NS3NaJ3IK",
			"Ztu2mn_gn",
		],
		optionTitles: ["Default", "1", "2", "3", "4", "5"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerx0ojEp2zn,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...AccordianFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "AxdgMy9Ls",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var faq_default = ComponentWithRoot;
export { faq_default as default };
