// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6d1ac80c6e7bce05 "Projeto Chacal", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Menu' | 'On Open' | 'Variant' // Variant
 * click?: Function // Click
}} Props

 */
import { routes } from "./chunks/chunk-XLH7UDAO.js";

// virtual:hamburger
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/Ty2bVINDGdIkSzWpnJql/IKrLCITV3DNNS2EqL5sl/oec1mR9cN.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var cycleOrder = ["kG8UDrLKh", "qPQutCq8P", "VenK8uR4y"];
var serializationHash = "framer-xeIfE";
var variantClassNames = {
	kG8UDrLKh: "framer-v-3ysyb3",
	qPQutCq8P: "framer-v-7jcdto",
	VenK8uR4y: "framer-v-3sv7bk",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.6,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 1.5,
	ease: [0.8, 0.2, 0, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: -350,
	y: 0,
};
var transition3 = {
	delay: 0.05,
	duration: 1.5,
	ease: [0.8, 0.2, 0, 1],
	type: "tween",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var transition4 = {
	delay: 0.1,
	duration: 1.5,
	ease: [0.8, 0.2, 0, 1],
	type: "tween",
};
var animation3 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 0,
};
var transition5 = {
	delay: 0.18,
	duration: 1.5,
	ease: [0.8, 0.2, 0, 1],
	type: "tween",
};
var animation4 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition5,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"On Open": "qPQutCq8P",
	Menu: "kG8UDrLKh",
	Variant: "VenK8uR4y",
};
var getProps = ({ click, height, id, width, ...props }) => {
	return {
		...props,
		JayvS8WIL: click ?? props.JayvS8WIL,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "kG8UDrLKh",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, JayvS8WIL, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "kG8UDrLKh",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap14o7lzh = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (JayvS8WIL) {
			const res = await JayvS8WIL(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "qPQutCq8P") return false;
		return true;
	};
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-3ysyb3",
							className,
							classNames,
						)}
						data-framer-name={"Menu"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"kG8UDrLKh"}
						onTap={onTap14o7lzh}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								qPQutCq8P: {
									"data-framer-name": "On Open",
								},
								VenK8uR4y: {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1fpv3lu"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"Xkzpz04bm"}
							style={{
								borderBottomLeftRadius: 0.09,
								borderBottomRightRadius: 0.09,
								borderTopLeftRadius: 0.09,
								borderTopRightRadius: 0.09,
							}}
						>
							<MotionDivWithFXWithOptimizedAppearEffect
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation}
								className={"framer-1890xrt"}
								data-framer-appear-id={"1890xrt"}
								initial={animation1}
								layoutDependency={layoutDependency}
								layoutId={"dobNGpuWw"}
								optimized={true}
								style={{
									backgroundColor:
										"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
									borderBottomLeftRadius: 0.02,
									borderBottomRightRadius: 0.02,
									borderTopLeftRadius: 0.02,
									borderTopRightRadius: 0.02,
									rotate: 0,
								}}
								variants={{
									qPQutCq8P: {
										rotate: 45,
									},
									VenK8uR4y: {
										rotate: 0,
									},
								}}
								{...addPropertyOverrides(
									{
										qPQutCq8P: {
											animate: void 0,
											initial: void 0,
											optimized: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							{isDisplayed() && (
								<MotionDivWithFXWithOptimizedAppearEffect
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation2}
									className={"framer-yu9frx"}
									data-framer-appear-id={"yu9frx"}
									initial={animation1}
									layoutDependency={layoutDependency}
									layoutId={"TyT_5W_5s"}
									optimized={true}
									style={{
										backgroundColor:
											"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
										borderBottomLeftRadius: 0.02,
										borderBottomRightRadius: 0.02,
										borderTopLeftRadius: 0.02,
										borderTopRightRadius: 0.02,
									}}
								/>
							)}
							<MotionDivWithFXWithOptimizedAppearEffect
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation3}
								className={"framer-1le3xxy"}
								data-framer-appear-id={"1le3xxy"}
								initial={animation1}
								layoutDependency={layoutDependency}
								layoutId={"RH12jqV2H"}
								optimized={true}
								style={{
									backgroundColor:
										"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
									borderBottomLeftRadius: 0.02,
									borderBottomRightRadius: 0.02,
									borderTopLeftRadius: 0.02,
									borderTopRightRadius: 0.02,
									rotate: 0,
								}}
								variants={{
									qPQutCq8P: {
										rotate: -45,
									},
									VenK8uR4y: {
										rotate: 0,
									},
								}}
								{...addPropertyOverrides(
									{
										qPQutCq8P: {
											animate: void 0,
											initial: void 0,
											optimized: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							{isDisplayed() && (
								<MotionDivWithFXWithOptimizedAppearEffect
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation4}
									className={"framer-uoxpcb"}
									data-framer-appear-id={"uoxpcb"}
									initial={animation1}
									layoutDependency={layoutDependency}
									layoutId={"fcCv5xhNN"}
									optimized={true}
									style={{
										backgroundColor:
											"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
										borderBottomLeftRadius: 0.02,
										borderBottomRightRadius: 0.02,
										borderTopLeftRadius: 0.02,
										borderTopRightRadius: 0.02,
									}}
								/>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xeIfE.framer-6nc6j7, .framer-xeIfE .framer-6nc6j7 { display: block; }",
	".framer-xeIfE.framer-3ysyb3 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 20px; justify-content: center; padding: 0px; position: relative; width: 45px; }",
	".framer-xeIfE .framer-1fpv3lu { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: 100%; justify-content: space-between; max-width: 45px; overflow: hidden; padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-xeIfE .framer-1890xrt, .framer-xeIfE .framer-yu9frx, .framer-xeIfE .framer-1le3xxy, .framer-xeIfE .framer-uoxpcb { flex: none; height: 8%; overflow: visible; position: relative; width: 100%; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-xeIfE.framer-3ysyb3 { gap: 0px; } .framer-xeIfE.framer-3ysyb3 > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-xeIfE.framer-3ysyb3 > :first-child { margin-left: 0px; } .framer-xeIfE.framer-3ysyb3 > :last-child { margin-right: 0px; } }",
	".framer-xeIfE.framer-v-7jcdto .framer-1890xrt { height: 10%; left: calc(51.11111111111113% - 22px / 2); position: absolute; top: 9px; width: 22px; }",
	".framer-xeIfE.framer-v-7jcdto .framer-1le3xxy { height: 10%; left: calc(48.88888888888891% - 22px / 2); position: absolute; top: calc(50.00000000000002% - 10% / 2); width: 22px; }",
];
var Frameroec1mR9cN = withCSS(Component, css, "framer-xeIfE");
var stdin_default = Frameroec1mR9cN;
Frameroec1mR9cN.displayName = "Hamburger";
Frameroec1mR9cN.defaultProps = {
	height: 20,
	width: 45,
};
addPropertyControls(Frameroec1mR9cN, {
	variant: {
		options: ["kG8UDrLKh", "qPQutCq8P", "VenK8uR4y"],
		optionTitles: ["Menu", "On Open", "Variant"],
		title: "Variant",
		type: ControlType.Enum,
	},
	JayvS8WIL: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	Frameroec1mR9cN,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:hamburger
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "qPQutCq8P",
	xl: "kG8UDrLKh",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HamburgerFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var hamburger_default = ComponentWithRoot;
export { hamburger_default as default };
