// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6d1ac80c6e7bce05 "Projeto Chacal", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Tablet On Open' | 'Phone' | 'On Open' | 'Phone On Open' // Variant
 * click?: Function // Click
}} Props

 */
import { routes } from "./chunks/chunk-XLH7UDAO.js";

// virtual:navbar
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/htndHGnQ8fUOogF2IFLS/DGPrhcmCxNE0jpUJLBjw/MsxFdRagv.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/kPzc7pTUuGwBRIhanFDg/Ia5HGgDRtxREH1fUWUNj/oec1mR9cN.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var cycleOrder = ["kG8UDrLKh", "qPQutCq8P", "VenK8uR4y"];
var serializationHash = "framer-xeIfE";
var variantClassNames = {
	kG8UDrLKh: "framer-v-3ysyb3",
	qPQutCq8P: "framer-v-7jcdto",
	VenK8uR4y: "framer-v-3sv7bk",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.6,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 1.5,
	ease: [0.8, 0.2, 0, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: -350,
	y: 0,
};
var transition3 = {
	delay: 0.05,
	duration: 1.5,
	ease: [0.8, 0.2, 0, 1],
	type: "tween",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var transition4 = {
	delay: 0.1,
	duration: 1.5,
	ease: [0.8, 0.2, 0, 1],
	type: "tween",
};
var animation3 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 0,
};
var transition5 = {
	delay: 0.18,
	duration: 1.5,
	ease: [0.8, 0.2, 0, 1],
	type: "tween",
};
var animation4 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition5,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"On Open": "qPQutCq8P",
	Menu: "kG8UDrLKh",
	Variant: "VenK8uR4y",
};
var getProps = ({ click, height, id, width, ...props }) => {
	return {
		...props,
		JayvS8WIL: click ?? props.JayvS8WIL,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "kG8UDrLKh",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, JayvS8WIL, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "kG8UDrLKh",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap14o7lzh = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (JayvS8WIL) {
			const res = await JayvS8WIL(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "qPQutCq8P") return false;
		return true;
	};
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-3ysyb3",
							className,
							classNames,
						)}
						data-framer-name={"Menu"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"kG8UDrLKh"}
						onTap={onTap14o7lzh}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								qPQutCq8P: {
									"data-framer-name": "On Open",
								},
								VenK8uR4y: {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1fpv3lu"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"Xkzpz04bm"}
							style={{
								borderBottomLeftRadius: 0.09,
								borderBottomRightRadius: 0.09,
								borderTopLeftRadius: 0.09,
								borderTopRightRadius: 0.09,
							}}
						>
							<MotionDivWithFXWithOptimizedAppearEffect
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation}
								className={"framer-1890xrt"}
								data-framer-appear-id={"1890xrt"}
								initial={animation1}
								layoutDependency={layoutDependency}
								layoutId={"dobNGpuWw"}
								optimized={true}
								style={{
									backgroundColor:
										"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
									borderBottomLeftRadius: 0.02,
									borderBottomRightRadius: 0.02,
									borderTopLeftRadius: 0.02,
									borderTopRightRadius: 0.02,
									rotate: 0,
								}}
								variants={{
									qPQutCq8P: {
										rotate: 45,
									},
									VenK8uR4y: {
										rotate: 0,
									},
								}}
								{...addPropertyOverrides(
									{
										qPQutCq8P: {
											animate: void 0,
											initial: void 0,
											optimized: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							{isDisplayed() && (
								<MotionDivWithFXWithOptimizedAppearEffect
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation2}
									className={"framer-yu9frx"}
									data-framer-appear-id={"yu9frx"}
									initial={animation1}
									layoutDependency={layoutDependency}
									layoutId={"TyT_5W_5s"}
									optimized={true}
									style={{
										backgroundColor:
											"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
										borderBottomLeftRadius: 0.02,
										borderBottomRightRadius: 0.02,
										borderTopLeftRadius: 0.02,
										borderTopRightRadius: 0.02,
									}}
								/>
							)}
							<MotionDivWithFXWithOptimizedAppearEffect
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation3}
								className={"framer-1le3xxy"}
								data-framer-appear-id={"1le3xxy"}
								initial={animation1}
								layoutDependency={layoutDependency}
								layoutId={"RH12jqV2H"}
								optimized={true}
								style={{
									backgroundColor:
										"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
									borderBottomLeftRadius: 0.02,
									borderBottomRightRadius: 0.02,
									borderTopLeftRadius: 0.02,
									borderTopRightRadius: 0.02,
									rotate: 0,
								}}
								variants={{
									qPQutCq8P: {
										rotate: -45,
									},
									VenK8uR4y: {
										rotate: 0,
									},
								}}
								{...addPropertyOverrides(
									{
										qPQutCq8P: {
											animate: void 0,
											initial: void 0,
											optimized: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							{isDisplayed() && (
								<MotionDivWithFXWithOptimizedAppearEffect
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation4}
									className={"framer-uoxpcb"}
									data-framer-appear-id={"uoxpcb"}
									initial={animation1}
									layoutDependency={layoutDependency}
									layoutId={"fcCv5xhNN"}
									optimized={true}
									style={{
										backgroundColor:
											"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
										borderBottomLeftRadius: 0.02,
										borderBottomRightRadius: 0.02,
										borderTopLeftRadius: 0.02,
										borderTopRightRadius: 0.02,
									}}
								/>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xeIfE.framer-6nc6j7, .framer-xeIfE .framer-6nc6j7 { display: block; }",
	".framer-xeIfE.framer-3ysyb3 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 20px; justify-content: center; padding: 0px; position: relative; width: 45px; }",
	".framer-xeIfE .framer-1fpv3lu { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: 100%; justify-content: space-between; max-width: 45px; overflow: hidden; padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-xeIfE .framer-1890xrt, .framer-xeIfE .framer-yu9frx, .framer-xeIfE .framer-1le3xxy, .framer-xeIfE .framer-uoxpcb { flex: none; height: 8%; overflow: visible; position: relative; width: 100%; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-xeIfE.framer-3ysyb3 { gap: 0px; } .framer-xeIfE.framer-3ysyb3 > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-xeIfE.framer-3ysyb3 > :first-child { margin-left: 0px; } .framer-xeIfE.framer-3ysyb3 > :last-child { margin-right: 0px; } }",
	".framer-xeIfE.framer-v-7jcdto .framer-1890xrt { height: 10%; left: calc(51.11111111111113% - 22px / 2); position: absolute; top: 9px; width: 22px; }",
	".framer-xeIfE.framer-v-7jcdto .framer-1le3xxy { height: 10%; left: calc(48.88888888888891% - 22px / 2); position: absolute; top: calc(50.00000000000002% - 10% / 2); width: 22px; }",
];
var Frameroec1mR9cN = withCSS(Component, css, "framer-xeIfE");
var stdin_default = Frameroec1mR9cN;
Frameroec1mR9cN.displayName = "Hamburger";
Frameroec1mR9cN.defaultProps = {
	height: 20,
	width: 45,
};
addPropertyControls(Frameroec1mR9cN, {
	variant: {
		options: ["kG8UDrLKh", "qPQutCq8P", "VenK8uR4y"],
		optionTitles: ["Menu", "On Open", "Variant"],
		title: "Variant",
		type: ControlType.Enum,
	},
	JayvS8WIL: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	Frameroec1mR9cN,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/htndHGnQ8fUOogF2IFLS/DGPrhcmCxNE0jpUJLBjw/MsxFdRagv.js
var HamburgerFonts = getFonts(stdin_default);
var cycleOrder2 = [
	"vWBDM61px",
	"tZ54lNGIk",
	"E3VgOnC5P",
	"NmE94Qc0_",
	"AtrAjeHRN",
	"Dkii7dirZ",
];
var serializationHash2 = "framer-xwveq";
var variantClassNames2 = {
	AtrAjeHRN: "framer-v-zvzid",
	Dkii7dirZ: "framer-v-nnth4e",
	E3VgOnC5P: "framer-v-1oyc6ae",
	NmE94Qc0_: "framer-v-kbw8yn",
	tZ54lNGIk: "framer-v-db6gi",
	vWBDM61px: "framer-v-fe5hmr",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"On Open": "AtrAjeHRN",
	"Phone On Open": "Dkii7dirZ",
	"Tablet On Open": "E3VgOnC5P",
	Desktop: "vWBDM61px",
	Phone: "NmE94Qc0_",
	Tablet: "tZ54lNGIk",
};
var getProps2 = ({ click, height, id, width, ...props }) => {
	return {
		...props,
		I9perpauA: click ?? props.I9perpauA,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "vWBDM61px",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const { style, className, layoutId, variant, I9perpauA, ...restProps } =
		getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "vWBDM61px",
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const JayvS8WIL16g1eb0 = activeVariantCallback(async (...args) => {
		if (I9perpauA) {
			const res = await I9perpauA(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const ref1 = React2.useRef(null);
	const defaultLayoutId = React2.useId();
	const componentViewport = useComponentViewport2();
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.nav
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-fe5hmr",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"vWBDM61px"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								AtrAjeHRN: {
									"data-framer-name": "On Open",
								},
								Dkii7dirZ: {
									"data-framer-name": "Phone On Open",
								},
								E3VgOnC5P: {
									"data-framer-name": "Tablet On Open",
								},
								NmE94Qc0_: {
									"data-framer-name": "Phone",
								},
								tZ54lNGIk: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1162n1u"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"OR_zWTQIT"}
						>
							<Link
								href={{
									webPageId: "augiA20Il",
								}}
								nodeId={"qP1pMg0iO"}
							>
								<motion2.a
									className={"framer-jjw34j framer-rq6hwt"}
									data-framer-name={"Logo"}
									layoutDependency={layoutDependency}
									layoutId={"qP1pMg0iO"}
								>
									<Image
										background={{
											alt: "Logo ",
											fit: "fill",
											intrinsicHeight: 64,
											intrinsicWidth: 64,
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 80) - 0 - 44) / 2) +
													0 +
													0,
											),
											pixelHeight: 64,
											pixelWidth: 64,
											src: "https://framerusercontent.com/images/M0uczrufnnFB6n2wWTbBzM8Dzg.png",
										}}
										className={"framer-kz6occ"}
										data-framer-name={"Logo"}
										layoutDependency={layoutDependency}
										layoutId={"cO2CcBnKc"}
										{...addPropertyOverrides2(
											{
												Dkii7dirZ: {
													background: {
														alt: "Logo ",
														fit: "fill",
														intrinsicHeight: 64,
														intrinsicWidth: 64,
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 80) - 0 - 44) /
																	2 +
																	0 +
																	0) +
																0 +
																0,
														),
														pixelHeight: 64,
														pixelWidth: 64,
														src: "https://framerusercontent.com/images/M0uczrufnnFB6n2wWTbBzM8Dzg.png",
													},
												},
												NmE94Qc0_: {
													background: {
														alt: "Logo ",
														fit: "fill",
														intrinsicHeight: 64,
														intrinsicWidth: 64,
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 80) - 0 - 44) /
																	2 +
																	0 +
																	0) +
																0 +
																0,
														),
														pixelHeight: 64,
														pixelWidth: 64,
														src: "https://framerusercontent.com/images/M0uczrufnnFB6n2wWTbBzM8Dzg.png",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion2.a>
							</Link>
							<motion2.div
								className={"framer-h4ydzd"}
								data-framer-name={"Hamburger"}
								layoutDependency={layoutDependency}
								layoutId={"FEy6Z1FeO"}
							>
								<ComponentViewportProvider
									height={20}
									y={
										(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 80) - 0 - 44) / 2) +
										12 +
										0
									}
									{...addPropertyOverrides2(
										{
											Dkii7dirZ: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 80) - 0 - 44) / 2 +
														0 +
														0) +
													12 +
													0,
											},
											NmE94Qc0_: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 80) - 0 - 44) / 2 +
														0 +
														0) +
													12 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion2.div
										className={"framer-a6j3ow-container"}
										layoutDependency={layoutDependency}
										layoutId={"OJrdWyqNM-container"}
									>
										{_jsx2(stdin_default, {
											height: "100%",
											id: "OJrdWyqNM",
											JayvS8WIL: JayvS8WIL16g1eb0,
											layoutId: "OJrdWyqNM",
											variant: "kG8UDrLKh",
											width: "100%",
											...addPropertyOverrides2(
												{
													AtrAjeHRN: {
														variant: "qPQutCq8P",
													},
													Dkii7dirZ: {
														variant: "qPQutCq8P",
													},
													E3VgOnC5P: {
														variant: "qPQutCq8P",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</motion2.div>
								</ComponentViewportProvider>
							</motion2.div>
						</motion2.div>
					</motion2.nav>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xwveq.framer-rq6hwt, .framer-xwveq .framer-rq6hwt { display: block; }",
	".framer-xwveq.framer-fe5hmr { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 80px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1200px; }",
	".framer-xwveq .framer-1162n1u { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 1400px; overflow: hidden; padding: 0px 28px 0px 28px; position: relative; width: 1px; }",
	".framer-xwveq .framer-jjw34j { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-xwveq .framer-kz6occ { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 38px); overflow: visible; position: relative; width: 38px; }",
	".framer-xwveq .framer-h4ydzd { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-xwveq .framer-a6j3ow-container { flex: none; height: auto; position: relative; width: auto; z-index: 6; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-xwveq.framer-fe5hmr, .framer-xwveq .framer-jjw34j, .framer-xwveq .framer-h4ydzd { gap: 0px; } .framer-xwveq.framer-fe5hmr > *, .framer-xwveq .framer-jjw34j > *, .framer-xwveq .framer-h4ydzd > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-xwveq.framer-fe5hmr > :first-child, .framer-xwveq .framer-jjw34j > :first-child, .framer-xwveq .framer-h4ydzd > :first-child { margin-left: 0px; } .framer-xwveq.framer-fe5hmr > :last-child, .framer-xwveq .framer-jjw34j > :last-child, .framer-xwveq .framer-h4ydzd > :last-child { margin-right: 0px; } }",
	".framer-xwveq.framer-v-db6gi.framer-fe5hmr, .framer-xwveq.framer-v-1oyc6ae.framer-fe5hmr { width: 810px; }",
	".framer-xwveq.framer-v-db6gi .framer-1162n1u, .framer-xwveq.framer-v-1oyc6ae .framer-1162n1u { padding: 0px 24px 0px 24px; }",
	".framer-xwveq.framer-v-kbw8yn.framer-fe5hmr, .framer-xwveq.framer-v-nnth4e.framer-fe5hmr { flex-direction: column; width: 390px; }",
	".framer-xwveq.framer-v-kbw8yn .framer-1162n1u, .framer-xwveq.framer-v-nnth4e .framer-1162n1u { flex: none; padding: 0px 14px 0px 14px; width: 100%; }",
	".framer-xwveq.framer-v-kbw8yn .framer-jjw34j, .framer-xwveq.framer-v-nnth4e .framer-jjw34j { align-content: flex-start; align-items: flex-start; }",
	".framer-xwveq.framer-v-kbw8yn .framer-kz6occ, .framer-xwveq.framer-v-nnth4e .framer-kz6occ { height: var(--framer-aspect-ratio-supported, 44px); }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-xwveq.framer-v-kbw8yn.framer-fe5hmr { gap: 0px; } .framer-xwveq.framer-v-kbw8yn.framer-fe5hmr > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-xwveq.framer-v-kbw8yn.framer-fe5hmr > :first-child { margin-top: 0px; } .framer-xwveq.framer-v-kbw8yn.framer-fe5hmr > :last-child { margin-bottom: 0px; } }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-xwveq.framer-v-nnth4e.framer-fe5hmr { gap: 0px; } .framer-xwveq.framer-v-nnth4e.framer-fe5hmr > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-xwveq.framer-v-nnth4e.framer-fe5hmr > :first-child { margin-top: 0px; } .framer-xwveq.framer-v-nnth4e.framer-fe5hmr > :last-child { margin-bottom: 0px; } }",
];
var FramerMsxFdRagv = withCSS2(Component2, css2, "framer-xwveq");
var stdin_default2 = FramerMsxFdRagv;
FramerMsxFdRagv.displayName = "Navbar";
FramerMsxFdRagv.defaultProps = {
	height: 80,
	width: 1200,
};
addPropertyControls2(FramerMsxFdRagv, {
	variant: {
		options: [
			"vWBDM61px",
			"tZ54lNGIk",
			"E3VgOnC5P",
			"NmE94Qc0_",
			"AtrAjeHRN",
			"Dkii7dirZ",
		],
		optionTitles: [
			"Desktop",
			"Tablet",
			"Tablet On Open",
			"Phone",
			"On Open",
			"Phone On Open",
		],
		title: "Variant",
		type: ControlType2.Enum,
	},
	I9perpauA: {
		title: "Click",
		type: ControlType2.EventHandler,
	},
});
addFonts2(
	FramerMsxFdRagv,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...HamburgerFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navbar
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "NmE94Qc0_",
	md: "tZ54lNGIk",
	xl: "vWBDM61px",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavbarFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var navbar_default = ComponentWithRoot;
export { navbar_default as default };
