// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6d1ac80c6e7bce05 "Projeto Chacal", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Large' | 'Rectangle Large' | 'Rectangle Large Close' // Variant
 * background?: string // Background
}} Props

 */
import { routes } from "./chunks/chunk-XLH7UDAO.js";

// virtual:slide-top-animation
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ybuVA2uOS4voPgkWXF5a/foiX5gGpI7JuHjoW4Ylr/udRGzPN7p.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["nKrs_Tkyb", "lOO6QoBfK", "IvcGJnznM", "ZvvzdYxiW"];
var serializationHash = "framer-VKVMx";
var variantClassNames = {
	IvcGJnznM: "framer-v-7bnpih",
	lOO6QoBfK: "framer-v-i2jasl",
	nKrs_Tkyb: "framer-v-paatbk",
	ZvvzdYxiW: "framer-v-mqm466",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 2,
	ease: [0.8, 0.2, 0, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.3,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.3,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 0,
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 570,
};
var animation3 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 570,
};
var animation4 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 900,
};
var animation5 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 900,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Rectangle Large Close": "ZvvzdYxiW",
	"Rectangle Large": "IvcGJnznM",
	Default: "nKrs_Tkyb",
	Large: "lOO6QoBfK",
};
var getProps = ({ background, height, id, width, ...props }) => {
	return {
		...props,
		fQzCw96Mu:
			background ??
			props.fQzCw96Mu ??
			"var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(247, 247, 242))",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "nKrs_Tkyb",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, fQzCw96Mu, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "nKrs_Tkyb",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (["IvcGJnznM", "ZvvzdYxiW"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (["IvcGJnznM", "ZvvzdYxiW"].includes(baseVariant)) return false;
		return true;
	};
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-paatbk",
							className,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"nKrs_Tkyb"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								IvcGJnznM: {
									"data-framer-name": "Rectangle Large",
								},
								lOO6QoBfK: {
									"data-framer-name": "Large",
								},
								ZvvzdYxiW: {
									"data-framer-name": "Rectangle Large Close",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<MotionDivWithFX
								__framer__animate={{
									transition: transition1,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-1twszjr"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"S45T_CTjo"}
								style={{
									scale: 4,
								}}
								variants={{
									ZvvzdYxiW: {
										scale: 1,
									},
								}}
								{...addPropertyOverrides(
									{
										ZvvzdYxiW: {
											__framer__styleAppearEffectEnabled: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								{isDisplayed() && (
									<motion.div
										className={"framer-11dhy16"}
										layoutDependency={layoutDependency}
										layoutId={"vopdK_73O"}
										style={{
											backgroundColor: "rgb(255, 255, 255)",
										}}
										variants={{
											IvcGJnznM: {
												backgroundColor:
													"var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(239, 238, 236))",
											},
											ZvvzdYxiW: {
												backgroundColor:
													"var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(239, 238, 236))",
											},
										}}
									/>
								)}
								{isDisplayed() && (
									<motion.div
										className={"framer-q6l7cf"}
										layoutDependency={layoutDependency}
										layoutId={"zLEKKxaTt"}
										style={{
											backgroundColor:
												"var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(239, 238, 236))",
										}}
									/>
								)}
								{isDisplayed() && (
									<motion.div
										className={"framer-107cr6t"}
										layoutDependency={layoutDependency}
										layoutId={"unrHkD5qD"}
										style={{
											backgroundColor: "rgb(255, 255, 255)",
										}}
										variants={{
											IvcGJnznM: {
												backgroundColor:
													"var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(239, 238, 236))",
											},
											ZvvzdYxiW: {
												backgroundColor:
													"var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(239, 238, 236))",
											},
										}}
									/>
								)}
								{isDisplayed() && (
									<motion.div
										className={"framer-1os6lga"}
										layoutDependency={layoutDependency}
										layoutId={"qqpoJtfs1"}
										style={{
											backgroundColor:
												"var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(239, 238, 236))",
										}}
									/>
								)}
							</MotionDivWithFX>
						)}
						{isDisplayed1() && (
							<MotionDivWithFX
								__framer__animate={{
									transition: transition1,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation2}
								__framer__exit={animation3}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-1of33e4"}
								layoutDependency={layoutDependency}
								layoutId={"INNPTFvl8"}
								style={{
									backgroundColor: fQzCw96Mu,
								}}
								{...addPropertyOverrides(
									{
										lOO6QoBfK: {
											__framer__enter: animation4,
											__framer__exit: animation5,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-VKVMx.framer-1pxclri, .framer-VKVMx .framer-1pxclri { display: block; }",
	".framer-VKVMx.framer-paatbk { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 500px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 368px; }",
	".framer-VKVMx .framer-1twszjr { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-VKVMx .framer-11dhy16 { flex: none; height: 105px; overflow: visible; position: relative; width: 900px; }",
	".framer-VKVMx .framer-q6l7cf { bottom: 0px; flex: none; height: 250px; left: calc(50.00000000000002% - 100% / 2); overflow: visible; position: absolute; width: 100%; z-index: 1; }",
	".framer-VKVMx .framer-107cr6t { flex: none; height: 700px; overflow: visible; position: relative; width: 300px; }",
	".framer-VKVMx .framer-1os6lga { flex: none; height: 100%; overflow: visible; position: absolute; right: 0px; top: calc(50.00000000000002% - 100% / 2); width: 37%; z-index: 1; }",
	".framer-VKVMx .framer-1of33e4 { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: visible; position: absolute; top: -570px; width: 100%; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-VKVMx.framer-paatbk, .framer-VKVMx .framer-1twszjr { gap: 0px; } .framer-VKVMx.framer-paatbk > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-VKVMx.framer-paatbk > :first-child, .framer-VKVMx .framer-1twszjr > :first-child { margin-left: 0px; } .framer-VKVMx.framer-paatbk > :last-child, .framer-VKVMx .framer-1twszjr > :last-child { margin-right: 0px; } .framer-VKVMx .framer-1twszjr > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } }",
	".framer-VKVMx.framer-v-i2jasl.framer-paatbk, .framer-VKVMx.framer-v-7bnpih.framer-paatbk, .framer-VKVMx.framer-v-mqm466.framer-paatbk { height: 700px; width: 1200px; }",
	".framer-VKVMx.framer-v-i2jasl .framer-1of33e4 { top: -900px; }",
	".framer-VKVMx.framer-v-7bnpih .framer-11dhy16 { height: 36%; left: calc(50.00000000000002% - 100% / 2); position: absolute; top: 1px; width: 100%; z-index: 1; }",
	".framer-VKVMx.framer-v-7bnpih .framer-q6l7cf { height: 36%; }",
	".framer-VKVMx.framer-v-7bnpih .framer-107cr6t { height: 100%; left: 0px; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 37%; z-index: 1; }",
	".framer-VKVMx.framer-v-mqm466 .framer-11dhy16 { height: 50%; left: calc(50.00000000000002% - 100% / 2); position: absolute; top: 1px; width: 100%; z-index: 1; }",
	".framer-VKVMx.framer-v-mqm466 .framer-q6l7cf { height: 50%; }",
	".framer-VKVMx.framer-v-mqm466 .framer-107cr6t { height: 100%; left: 0px; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 50%; z-index: 1; }",
	".framer-VKVMx.framer-v-mqm466 .framer-1os6lga { width: 50%; }",
];
var FramerudRGzPN7p = withCSS(Component, css, "framer-VKVMx");
var stdin_default = FramerudRGzPN7p;
FramerudRGzPN7p.displayName = "Slide Top Animation";
FramerudRGzPN7p.defaultProps = {
	height: 500,
	width: 368,
};
addPropertyControls(FramerudRGzPN7p, {
	variant: {
		options: ["nKrs_Tkyb", "lOO6QoBfK", "IvcGJnznM", "ZvvzdYxiW"],
		optionTitles: [
			"Default",
			"Large",
			"Rectangle Large",
			"Rectangle Large Close",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	fQzCw96Mu: {
		defaultValue:
			"var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(247, 247, 242))",
		title: "Background",
		type: ControlType.Color,
	},
});
addFonts(
	FramerudRGzPN7p,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:slide-top-animation
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "IvcGJnznM",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SlideTopAnimationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var slide_top_animation_default = ComponentWithRoot;
export { slide_top_animation_default as default };
