// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6d1ac80c6e7bce05 "Projeto Chacal", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * name?: string // Name
 * role?: string // Role
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-XO7AUMAJ.js";
import { routes } from "./chunks/chunk-XLH7UDAO.js";

// virtual:team-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/6EO8qvsMeD42qY8nvTJx/2KWbXBorVVz5HHV32tMV/hPyww5R_H.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-WbEAV";
var variantClassNames = {
	c5IshuW3o: "framer-v-23sv8z",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, image, name1, role, width, ...props }) => {
	return {
		...props,
		JB3OScX6N: name1 ?? props.JB3OScX6N ?? "Ava Carter",
		tAYZ7l3QJ: image ??
			props.tAYZ7l3QJ ?? {
				alt: "",
				src: "https://framerusercontent.com/images/y0WmAsGbLha7A3tEYuKr6kpSqik.png?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/y0WmAsGbLha7A3tEYuKr6kpSqik.png?scale-down-to=1024 771w,https://framerusercontent.com/images/y0WmAsGbLha7A3tEYuKr6kpSqik.png?scale-down-to=2048 1542w,https://framerusercontent.com/images/y0WmAsGbLha7A3tEYuKr6kpSqik.png 1856w",
			},
		ZhGVsSe_A: role ?? props.ZhGVsSe_A ?? "Creative Director",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		tAYZ7l3QJ,
		JB3OScX6N,
		ZhGVsSe_A,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "c5IshuW3o",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-23sv8z",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"c5IshuW3o"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 344) - 0 - 344) / 2 +
											0 +
											0),
								),
								pixelHeight: 2464,
								pixelWidth: 1856,
								sizes: componentViewport?.width || "100vw",
								...toResponsiveImage(tAYZ7l3QJ),
							}}
							className={"framer-17t61i9"}
							layoutDependency={layoutDependency}
							layoutId={"CSED7SNCD"}
						/>
						<motion.div
							className={"framer-ee5xdw"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"wllQwGdMJ"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-ffnrmh"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"L1wdIydl_"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={JB3OScX6N}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-q12std"}
										data-styles-preset={"nZjNjGRCH"}
										style={{
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223)))",
										}}
									>
										{"Ava Carter"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1xmi39z"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"ErjWQUewj"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={ZhGVsSe_A}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-q12std"}
										data-styles-preset={"nZjNjGRCH"}
										style={{
											"--framer-text-alignment": "right",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-183b5922-d0ea-48d1-af7c-77d51908fd54, rgb(226, 225, 223)))",
										}}
									>
										{"Creative Director"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-WbEAV.framer-hv9uee, .framer-WbEAV .framer-hv9uee { display: block; }",
	".framer-WbEAV.framer-23sv8z { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 275px; }",
	".framer-WbEAV .framer-17t61i9 { flex: none; height: 344px; overflow: hidden; position: relative; width: 100%; }",
	".framer-WbEAV .framer-ee5xdw { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; height: 100%; justify-content: space-between; left: calc(49.81818181818184% - 100% / 2); overflow: hidden; padding: 14px; position: absolute; width: 100%; z-index: 3; }",
	".framer-WbEAV .framer-ffnrmh, .framer-WbEAV .framer-1xmi39z { --framer-text-wrap-override: none; flex: none; height: auto; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-WbEAV.framer-23sv8z { gap: 0px; } .framer-WbEAV.framer-23sv8z > * { margin: 0px; margin-bottom: calc(14px / 2); margin-top: calc(14px / 2); } .framer-WbEAV.framer-23sv8z > :first-child { margin-top: 0px; } .framer-WbEAV.framer-23sv8z > :last-child { margin-bottom: 0px; } }",
	...css,
];
var FramerhPyww5R_H = withCSS(Component, css2, "framer-WbEAV");
var stdin_default = FramerhPyww5R_H;
FramerhPyww5R_H.displayName = "Team Card";
FramerhPyww5R_H.defaultProps = {
	height: 344,
	width: 275,
};
addPropertyControls(FramerhPyww5R_H, {
	tAYZ7l3QJ: {
		__defaultAssetReference:
			"data:framer/asset-reference,y0WmAsGbLha7A3tEYuKr6kpSqik.png?originalFilename=QmbvWqaAMzAG83Gezrn27c64kQqPtvVCBXLBqtvZHi7Yrd.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,y0WmAsGbLha7A3tEYuKr6kpSqik.png?originalFilename=QmbvWqaAMzAG83Gezrn27c64kQqPtvVCBXLBqtvZHi7Yrd.png&preferredSize=auto",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	JB3OScX6N: {
		defaultValue: "Ava Carter",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	ZhGVsSe_A: {
		defaultValue: "Creative Director",
		displayTextArea: false,
		title: "Role",
		type: ControlType.String,
	},
});
addFonts(
	FramerhPyww5R_H,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:team-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TeamCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var team_card_default = ComponentWithRoot;
export { team_card_default as default };
