// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6d1ac80c6e7bce05 "Projeto Chacal", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Tablet' | 'Mobile' // Variant
 * link?: string // Link
 * title?: string // Title
 * click?: Function // Click
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-TWQC6X2U.js";
import { routes } from "./chunks/chunk-XLH7UDAO.js";

// virtual:title-link
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/qHqDoPAaR5q456BYDCBA/IRWrhvkysg2Gck3xIHpj/guLyNxC8y.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(RichText),
);
var enabledGestures = {
	EFA8oVtzT: {
		hover: true,
	},
	SevxyGrsl: {
		hover: true,
	},
	XN_C0vk7P: {
		hover: true,
	},
};
var cycleOrder = ["XN_C0vk7P", "SevxyGrsl", "EFA8oVtzT"];
var serializationHash = "framer-ksWl2";
var variantClassNames = {
	EFA8oVtzT: "framer-v-1tom62h",
	SevxyGrsl: "framer-v-1fzrv5a",
	XN_C0vk7P: "framer-v-1g56wky",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.5,
	ease: [0.8, 0.6, 0, 1],
	type: "tween",
};
var transition2 = {
	delay: 0.4,
	duration: 1.5,
	ease: [0.8, 0.2, 0, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 80,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "XN_C0vk7P",
	Mobile: "EFA8oVtzT",
	Tablet: "SevxyGrsl",
};
var getProps = ({ click, height, id, link, title, width, ...props }) => {
	return {
		...props,
		HLmw1UWOq: click ?? props.HLmw1UWOq,
		qVdNB6FgL: link ?? props.qVdNB6FgL,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "XN_C0vk7P",
		YRglBSliG: title ?? props.YRglBSliG ?? "HOME",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		qVdNB6FgL,
		YRglBSliG,
		HLmw1UWOq,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "XN_C0vk7P",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap2zajx3 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (HLmw1UWOq) {
			const res = await HLmw1UWOq(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1g56wky",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"XN_C0vk7P"}
						onTap={onTap2zajx3}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"EFA8oVtzT-hover": {
									"data-framer-name": void 0,
								},
								"SevxyGrsl-hover": {
									"data-framer-name": void 0,
								},
								"XN_C0vk7P-hover": {
									"data-framer-name": void 0,
								},
								EFA8oVtzT: {
									"data-framer-name": "Mobile",
								},
								SevxyGrsl: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Link href={qVdNB6FgL} nodeId={"W4xAaNzkm"}>
							<motion.a
								aria-label={"Button"}
								className={"framer-1u6d4w framer-1hzufgj"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"W4xAaNzkm"}
							>
								<RichTextWithFXWithOptimizedAppearEffect
									__fromCanvasComponent={true}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation}
									className={"framer-1bpvt82"}
									data-framer-appear-id={"1bpvt82"}
									fonts={["Inter"]}
									initial={animation1}
									layoutDependency={layoutDependency}
									layoutId={"MInxrTbTp"}
									optimized={true}
									style={{
										"--extracted-a0htzi":
											"var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(247, 247, 242))",
									}}
									text={YRglBSliG}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h3
											className={"framer-styles-preset-quploe"}
											data-styles-preset={"ksrCBwsI2"}
											style={{
												"--framer-text-color":
													"var(--extracted-a0htzi, var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(247, 247, 242)))",
											}}
										>
											{"HOME"}
										</motion.h3>
									</React.Fragment>
								</RichTextWithFXWithOptimizedAppearEffect>
								<RichTextWithFXWithOptimizedAppearEffect
									__fromCanvasComponent={true}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation}
									className={"framer-1vcrp30"}
									data-framer-appear-id={"1vcrp30"}
									fonts={["Inter"]}
									initial={animation1}
									layoutDependency={layoutDependency}
									layoutId={"qMMC16jRr"}
									optimized={true}
									style={{
										"--extracted-a0htzi":
											"var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(247, 247, 242))",
									}}
									text={YRglBSliG}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h3
											className={"framer-styles-preset-quploe"}
											data-styles-preset={"ksrCBwsI2"}
											style={{
												"--framer-text-color":
													"var(--extracted-a0htzi, var(--token-e7580645-294b-4fb1-bde8-c21a5a3f7676, rgb(247, 247, 242)))",
											}}
										>
											{"HOME"}
										</motion.h3>
									</React.Fragment>
								</RichTextWithFXWithOptimizedAppearEffect>
							</motion.a>
						</Link>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ksWl2.framer-1hzufgj, .framer-ksWl2 .framer-1hzufgj { display: block; }",
	".framer-ksWl2.framer-1g56wky { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-ksWl2 .framer-1u6d4w { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 56px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-ksWl2 .framer-1bpvt82, .framer-ksWl2 .framer-1vcrp30 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ksWl2.framer-1g56wky, .framer-ksWl2 .framer-1u6d4w { gap: 0px; } .framer-ksWl2.framer-1g56wky > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-ksWl2.framer-1g56wky > :first-child { margin-left: 0px; } .framer-ksWl2.framer-1g56wky > :last-child { margin-right: 0px; } .framer-ksWl2 .framer-1u6d4w > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-ksWl2 .framer-1u6d4w > :first-child { margin-top: 0px; } .framer-ksWl2 .framer-1u6d4w > :last-child { margin-bottom: 0px; } }",
	".framer-ksWl2.framer-v-1fzrv5a .framer-1u6d4w { height: 44px; }",
	".framer-ksWl2.framer-v-1tom62h .framer-1u6d4w { height: 32px; }",
	".framer-ksWl2.framer-v-1g56wky.hover .framer-1u6d4w, .framer-ksWl2.framer-v-1fzrv5a.hover .framer-1u6d4w, .framer-ksWl2.framer-v-1tom62h.hover .framer-1u6d4w { justify-content: flex-end; }",
	...css,
];
var FramerguLyNxC8y = withCSS(Component, css2, "framer-ksWl2");
var stdin_default = FramerguLyNxC8y;
FramerguLyNxC8y.displayName = "Title Link";
FramerguLyNxC8y.defaultProps = {
	height: 56,
	width: 146,
};
addPropertyControls(FramerguLyNxC8y, {
	variant: {
		options: ["XN_C0vk7P", "SevxyGrsl", "EFA8oVtzT"],
		optionTitles: ["Default", "Tablet", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	qVdNB6FgL: {
		title: "Link",
		type: ControlType.Link,
	},
	YRglBSliG: {
		defaultValue: "HOME",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	HLmw1UWOq: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerguLyNxC8y,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:title-link
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "EFA8oVtzT",
	md: "SevxyGrsl",
	xl: "XN_C0vk7P",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TitleLinkFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6d1ac80c6e7bce05cf1e83998b9524564a80e103f40bc586c8c0153e682ec4cd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var title_link_default = ComponentWithRoot;
export { title_link_default as default };
