name: Build and release preview
permissions:
  contents: write

on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run framer
      - run: bun run build
      - run: bunx unframer-deploy-demo@latest --secret 2d28f01326ea0eaf --slug projeto-chacal-6d1ac --dir ./dist
      - name: Commit & push (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          # Optional: avoid non-fast-forward errors if something landed meanwhile
          git pull --rebase origin "${{ github.ref_name }}" || true

          # Add [skip ci] to the commit message to skip ci runs on this commit
          git commit -m "chore: automated update [skip ci]"
          git push origin HEAD:"${{ github.ref_name }}"